using Data.Services.Grid;

namespace ART_PACKAGE.Helpers.ReportsConfigurations
{
    public class artauditcorporateviewConfig : ReportConfig
    {
        public artauditcorporateviewConfig()
        {



            DisplayNames = new Dictionary<string, GridColumnConfiguration>(){ {"CaseRk" , new GridColumnConfiguration { DisplayName = "Case Rk"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"BankingOrCorporate" , new GridColumnConfiguration { DisplayName = "Banking Or Corporate"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"ClientNumber" , new GridColumnConfiguration { DisplayName = "Client Number"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"NameLanguage" , new GridColumnConfiguration { DisplayName = "Name Language"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"CorporateName" , new GridColumnConfiguration { DisplayName = "Corporate Name"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"CommercialName" , new GridColumnConfiguration { DisplayName = "Commercial Name"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"CorporateNameEn" , new GridColumnConfiguration { DisplayName = "Corporate Name En"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"CommercialNameEn" , new GridColumnConfiguration { DisplayName = "Commercial Name En"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Title" , new GridColumnConfiguration { DisplayName = "Title"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"DefaultBranch" , new GridColumnConfiguration { DisplayName = "Default Branch"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Industry" , new GridColumnConfiguration { DisplayName = "Industry"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"AmlRiskCd" , new GridColumnConfiguration { DisplayName = "Aml Risk CD"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"KycStatus" , new GridColumnConfiguration { DisplayName = "Kyc Status"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"TypeOfBusiness" , new GridColumnConfiguration { DisplayName = "Type Of Business"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"TypeOfBusinessOther" , new GridColumnConfiguration { DisplayName = "Type Of Business Other"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"IdentType" , new GridColumnConfiguration { DisplayName = "Identity Type"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"IdentNumber" , new GridColumnConfiguration { DisplayName = "Identity Number"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"IdIssueCountry" , new GridColumnConfiguration { DisplayName = "ID Issue Country"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"IdentIssueDate" , new GridColumnConfiguration { DisplayName = "Identity Issue Date"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"IdentExpiryDate" , new GridColumnConfiguration { DisplayName = "Identity Expiry Date"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"RegNumberCity" , new GridColumnConfiguration { DisplayName = "Reg Number City"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"RegNumberOffice" , new GridColumnConfiguration { DisplayName = "Reg Number Office"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"RegistrationNumber" , new GridColumnConfiguration { DisplayName = "Registration Number"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"RegExpiryDate" , new GridColumnConfiguration { DisplayName = "Reg Expiry Date"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"RegNumberLastDate" , new GridColumnConfiguration { DisplayName = "Reg Number Last Date"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"HeadQuarterCountry" , new GridColumnConfiguration { DisplayName = "Head Quarter Country"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"TaxIdNum" , new GridColumnConfiguration { DisplayName = "Tax ID Number"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"NationalityCountry" , new GridColumnConfiguration { DisplayName = "Nationality Country"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"IncorporationCountryCode" , new GridColumnConfiguration { DisplayName = "Incorporation Country Code"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"IncorporationDate" , new GridColumnConfiguration { DisplayName = "Incorporation Date"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"IncorporationLegalForm" , new GridColumnConfiguration { DisplayName = "Incorporation Legal Form"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"IncorporationState" , new GridColumnConfiguration { DisplayName = "Incorporation State"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"LegalFormOthers" , new GridColumnConfiguration { DisplayName = "Legal Form Others"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"LegalFormSub" , new GridColumnConfiguration { DisplayName = "Legal Form Sub"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"RiskReason" , new GridColumnConfiguration { DisplayName = "Risk Reason"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"RiskCode" , new GridColumnConfiguration { DisplayName = "Risk Code"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"CbRiskRate" , new GridColumnConfiguration { DisplayName = "Cb Risk Rate"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"ClosingReasonId" , new GridColumnConfiguration { DisplayName = "Closing Reason ID"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"CloseDate" , new GridColumnConfiguration { DisplayName = "Close Date"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"CreateDate" , new GridColumnConfiguration { DisplayName = "Create Date"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"CreatedBy" , new GridColumnConfiguration { DisplayName = "Created By"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"NextUpdateDate" , new GridColumnConfiguration { DisplayName = "Next Update Date"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"UpdateDate" , new GridColumnConfiguration { DisplayName = "Update Date"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"UpdatedBy" , new GridColumnConfiguration { DisplayName = "Updated By"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"ActivityTypeSub" , new GridColumnConfiguration { DisplayName = "Activity Type Sub"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"BudgetDate1" , new GridColumnConfiguration { DisplayName = "Budget Date1"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"BudgetDate2" , new GridColumnConfiguration { DisplayName = "Budget Date2"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"BudgetDate3" , new GridColumnConfiguration { DisplayName = "Budget Date3"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"FfiType" , new GridColumnConfiguration { DisplayName = "Ffi Type"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Giin" , new GridColumnConfiguration { DisplayName = "Giin"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"SalesVolume1" , new GridColumnConfiguration { DisplayName = "Sales Volume1"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"SalesVolume2" , new GridColumnConfiguration { DisplayName = "Sales Volume2"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"SalesVolume3" , new GridColumnConfiguration { DisplayName = "Sales Volume3"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"ActivityAmount" , new GridColumnConfiguration { DisplayName = "Activity Amount"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"ActivityAmountCurrency" , new GridColumnConfiguration { DisplayName = "Activity Amount Currency"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"ActivityEndDate" , new GridColumnConfiguration { DisplayName = "Activity End Date"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"ActivityStartDate" , new GridColumnConfiguration { DisplayName = "Activity Start Date"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"ActivityType" , new GridColumnConfiguration { DisplayName = "Activity Type"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"ActivityTypeDtls" , new GridColumnConfiguration { DisplayName = "Activity Type Dtls"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"CharityDonationsInd" , new GridColumnConfiguration { DisplayName = "Charity Donations Ind"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"FinancialStartDate" , new GridColumnConfiguration { DisplayName = "Financial Start Date"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"ForeignConsulateEmbassyInd" , new GridColumnConfiguration { DisplayName = "Foreign Consulate Embassy Ind"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"GovOrgInd" , new GridColumnConfiguration { DisplayName = "Gov Org Ind"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"WomenShare" , new GridColumnConfiguration { DisplayName = "Women Share"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"DateOfBudget" , new GridColumnConfiguration { DisplayName = "Date Of Budget"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"NoOfEmployees" , new GridColumnConfiguration { DisplayName = "No Of Employees"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"SizeOfSales" , new GridColumnConfiguration { DisplayName = "Size Of Sales"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"SizeOfTransaction" , new GridColumnConfiguration { DisplayName = "Size Of Transaction"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"ReferenceEmployeeId" , new GridColumnConfiguration { DisplayName = "Reference Employee ID"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"CustomerReference" , new GridColumnConfiguration { DisplayName = "Customer Reference"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"BankingOrOtherRef" , new GridColumnConfiguration { DisplayName = "Banking Or Other Ref"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"LimitsAmount" , new GridColumnConfiguration { DisplayName = "Limits Amount"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"LimitsAmountCurrency" , new GridColumnConfiguration { DisplayName = "Limits Amount Currency"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"GeoCode" , new GridColumnConfiguration { DisplayName = "Geo Code"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"BusinessCode" , new GridColumnConfiguration { DisplayName = "Business Code"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"CalculateZakahFlag" , new GridColumnConfiguration { DisplayName = "Calculate Zakah Flag"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"CustomerStatus" , new GridColumnConfiguration { DisplayName = "Customer Status"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"InvestmentBalance" , new GridColumnConfiguration { DisplayName = "Investment Balance"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"SalesBasis" , new GridColumnConfiguration { DisplayName = "Sales Basis"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"LegalStepMainCode" , new GridColumnConfiguration { DisplayName = "Legal Step Main Code"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"LegalStepSubCode" , new GridColumnConfiguration { DisplayName = "Legal Step Sub Code"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"MainLegalForm" , new GridColumnConfiguration { DisplayName = "Main Legal Form"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"UnderEstablishment" , new GridColumnConfiguration { DisplayName = "Under Establishment"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"TotalNoOfUnits" , new GridColumnConfiguration { DisplayName = "Total No Of Units"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"RiskWeight" , new GridColumnConfiguration { DisplayName = "Risk Weight"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"WorthCode" , new GridColumnConfiguration { DisplayName = "Worth Code"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"LastQueryDate" , new GridColumnConfiguration { DisplayName = "Last Query Date"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"TradeAddDate" , new GridColumnConfiguration { DisplayName = "Trade Add Date"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"WorthLastCalcDate" , new GridColumnConfiguration { DisplayName = "Worth Last Calc Date"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"EconomicActivityCode5" , new GridColumnConfiguration { DisplayName = "Economic Activity Code5"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"PaidUpCapitalAmount" , new GridColumnConfiguration { DisplayName = "Paid Up Capital Amount"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"PaidUpCapitalCurrency" , new GridColumnConfiguration { DisplayName = "Paid Up Capital Currency"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"DealtBankDetails" , new GridColumnConfiguration { DisplayName = "Dealt Bank Details"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"DealAbrdBankDetails" , new GridColumnConfiguration { DisplayName = "Deal Abrd Bank Details"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"OtherBankAccounts" , new GridColumnConfiguration { DisplayName = "Other Bank Accounts"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Capital1" , new GridColumnConfiguration { DisplayName = "Capital1"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Capital2" , new GridColumnConfiguration { DisplayName = "Capital2"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Capital3" , new GridColumnConfiguration { DisplayName = "Capital3"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"AnnualNetIncomeCd" , new GridColumnConfiguration { DisplayName = "Annual Net Income CD"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"NonProfitOrganization" , new GridColumnConfiguration { DisplayName = "Non Profit Organization"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"CompanyStock" , new GridColumnConfiguration { DisplayName = "Company Stock"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"CompanyStockName" , new GridColumnConfiguration { DisplayName = "Company Stock Name"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"HoldingCorporation" , new GridColumnConfiguration { DisplayName = "Holding Corporation"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"HoldingCorporationCd" , new GridColumnConfiguration { DisplayName = "Holding Corporation CD"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } } };







        }
    }
}