namespace ART_PACKAGE.Helpers.ReportsConfigurations
{
    public class arttifinaninteraccrualConfig : ReportConfig
    {
        public arttifinaninteraccrualConfig()
        {

            SkipList = new List<string>(){ "Inttypeid",
"Calcdte",
"EarlyDate",
"RecamtPd",
"RecccyPd",
"RecamtPdEgp",
"Gfcun",
"CusMnm",
"SwBank",
"SwCtr",
"SwLoc",
"SwBranch",
"Recamt",
"DealCcy",
"IntpAmt",
"IntpCcy",
"IntpAmtEgp",
"Cycleend",
"Pastduedte",
"Extraday",
"IntType",
"RateType",
"PartpnRef",
"Ptnshare",
"Prodtypename",
"Idb",
"Intperunit",
"Intpernum",
"Intperday",
"CcySpt",
"CcySei",
"BhalfBrn",
"Sovalue",
"CcyCed",
"CalcdtePd",
"Calcrate",
"Actualrate",
"Prodtypedesc",
"BaseRate2",
"DiffRate2",
"GroupRate2",
"BalancAmt",
"SplitTier",
"TierNum",
"TierAmt",
"Pedoramt",
"TierPnum",
"TierPunit",
"TierBase",
"TierDiff",
"TierSprd",
"TierRate",
"GroupCode",
"Schratetype",
"Calcrate1",
"Interp",
"Interprate",
"Commitamt",
"AmtOrPct" };

            DisplayNames = new Dictionary<string, GridColumnConfiguration>(){ {"BranchName" , new GridColumnConfiguration { DisplayName = "Branch Name"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"MasterRef" , new GridColumnConfiguration { DisplayName = "Master Reference"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Startdate" , new GridColumnConfiguration { DisplayName = "Start Date"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Maturity" , new GridColumnConfiguration { DisplayName = "Maturity Date"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Prodcut" , new GridColumnConfiguration { DisplayName = "Product"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"AmtOS" , new GridColumnConfiguration { DisplayName = "Outstanding Amount"  , Format = "{0:n2}"  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Recccy" , new GridColumnConfiguration { DisplayName = "Currency"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"AmtOSEgp" , new GridColumnConfiguration { DisplayName = "Outstanding Amount Egp"  , Format = "{0:n2}"  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Inttypeid" , new GridColumnConfiguration { DisplayName = "Inttypeid"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Calcdte" , new GridColumnConfiguration { DisplayName = "Calc Date"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"EarlyDate" , new GridColumnConfiguration { DisplayName = "Early Date"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"RecamtPd" , new GridColumnConfiguration { DisplayName = "RecamtPd"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"RecccyPd" , new GridColumnConfiguration { DisplayName = "RecccyPd"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"RecamtPdEgp" , new GridColumnConfiguration { DisplayName = "RecamtPdEgp"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Address1" , new GridColumnConfiguration { DisplayName = "Principal"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"InterestRateType" , new GridColumnConfiguration { DisplayName = "Interest Rate and Type"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Gfcun" , new GridColumnConfiguration { DisplayName = "Gfcun"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"CusMnm" , new GridColumnConfiguration { DisplayName = "CusMnm"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"SwBank" , new GridColumnConfiguration { DisplayName = "SwBank"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"SwCtr" , new GridColumnConfiguration { DisplayName = "SwCtr"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"SwLoc" , new GridColumnConfiguration { DisplayName = "SwLoc"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"SwBranch" , new GridColumnConfiguration { DisplayName = "SwBranch"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Recamt" , new GridColumnConfiguration { DisplayName = "Recamt"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"DealCcy" , new GridColumnConfiguration { DisplayName = "DealCcy"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"IntpAmt" , new GridColumnConfiguration { DisplayName = "IntpAmt"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"IntpCcy" , new GridColumnConfiguration { DisplayName = "IntpCcy"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"IntpAmtEgp" , new GridColumnConfiguration { DisplayName = "IntpAmtEgp"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Cycleend" , new GridColumnConfiguration { DisplayName = "Cycleend"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Pastduedte" , new GridColumnConfiguration { DisplayName = "Pastduedte"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Extraday" , new GridColumnConfiguration { DisplayName = "Extraday"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"IntType" , new GridColumnConfiguration { DisplayName = "IntType"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"RateType" , new GridColumnConfiguration { DisplayName = "RateType"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"PartpnRef" , new GridColumnConfiguration { DisplayName = "PartpnRef"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Ptnshare" , new GridColumnConfiguration { DisplayName = "Ptnshare"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Prodtypename" , new GridColumnConfiguration { DisplayName = "Prodtypename"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Idb" , new GridColumnConfiguration { DisplayName = "Idb"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Intperunit" , new GridColumnConfiguration { DisplayName = "Intperunit"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Intpernum" , new GridColumnConfiguration { DisplayName = "Intpernum"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Intperday" , new GridColumnConfiguration { DisplayName = "Intperday"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"CcySpt" , new GridColumnConfiguration { DisplayName = "CcySpt"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"CcySei" , new GridColumnConfiguration { DisplayName = "CcySei"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"BhalfBrn" , new GridColumnConfiguration { DisplayName = "BhalfBrn"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Sovalue" , new GridColumnConfiguration { DisplayName = "Sovalue"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"CcyCed" , new GridColumnConfiguration { DisplayName = "CcyCed"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"CalcdtePd" , new GridColumnConfiguration { DisplayName = "CalcdtePd"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Calcrate" , new GridColumnConfiguration { DisplayName = "Calcrate"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Actualrate" , new GridColumnConfiguration { DisplayName = "Actualrate"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Prodtypedesc" , new GridColumnConfiguration { DisplayName = "Prodtypedesc"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"BaseRate2" , new GridColumnConfiguration { DisplayName = "BaseRate2"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"DiffRate2" , new GridColumnConfiguration { DisplayName = "DiffRate2"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"GroupRate2" , new GridColumnConfiguration { DisplayName = "GroupRate2"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"BalancAmt" , new GridColumnConfiguration { DisplayName = "BalancAmt"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"SplitTier" , new GridColumnConfiguration { DisplayName = "SplitTier"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"TierNum" , new GridColumnConfiguration { DisplayName = "TierNum"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"TierAmt" , new GridColumnConfiguration { DisplayName = "TierAmt"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Pedoramt" , new GridColumnConfiguration { DisplayName = "Pedoramt"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"TierPnum" , new GridColumnConfiguration { DisplayName = "TierPnum"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"TierPunit" , new GridColumnConfiguration { DisplayName = "TierPunit"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"TierBase" , new GridColumnConfiguration { DisplayName = "TierBase"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"TierDiff" , new GridColumnConfiguration { DisplayName = "TierDiff"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"TierSprd" , new GridColumnConfiguration { DisplayName = "TierSprd"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"TierRate" , new GridColumnConfiguration { DisplayName = "TierRate"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"GroupCode" , new GridColumnConfiguration { DisplayName = "GroupCode"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Schratetype" , new GridColumnConfiguration { DisplayName = "Schratetype"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Calcrate1" , new GridColumnConfiguration { DisplayName = "Calcrate1"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Interp" , new GridColumnConfiguration { DisplayName = "Interp"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Interprate" , new GridColumnConfiguration { DisplayName = "Interprate"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Commitamt" , new GridColumnConfiguration { DisplayName = "Commitamt"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"AmtOrPct" , new GridColumnConfiguration { DisplayName = "AmtOrPct"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } } };







        }
    }
}