namespace ART_PACKAGE.Helpers.ReportsConfigurations
{
    public class arttisystemtailoringreportConfig : ReportConfig
    {
        public arttisystemtailoringreportConfig()
        {

            SkipList = new List<string>(){ "Typeflag",
"Operat44",
"Seq97",
"Canamdbas",
"Amendchg",
"Autoprint",
"Severity",
"ErrorText",
"Deadlinedays",
"Deadlinedate",
"Deadlinetime",
"Deadlinersecs",
"Useevtfm",
"Username",
"Teamcode",
"Obsolete",
"Relevmapkey",
"Steptype",
"Amberdays",
"Amberdate",
"Ambertime",
"Amberrsecs",
"Reddays",
"Reddate",
"Redtime",
"Redrsecs",
"Paramsetid",
"Mappingid",
"Inuse",
"Intinitstepid",
"Swinitstepid",
"Btinitstepid",
"Gwinitstepid",
"Swrejstepid",
"Btrejstepid",
"Gwrejstepid",
"Mapstepid",
"StepTime",
"AvailType",
"Teamdescr",
"Mappingsubid",
"Debitcredit",
"Trancode",
"RevPstngs",
"InternAcc",
"Contingent",
"Liability",
"ChkLimit",
"Postingtyp",
"Margin",
"Trcrsdliab",
"TransAcc",
"Projection",
"Sequence",
"Rejstepid",
"ActualAmt",
"AmtCcy",
"Mapstepdescr",
"Rejstepdescr",
"Intinitstepdescr",
"Swinitstepdescr",
"Btinitstepdescr",
"Gwinitstepdescr",
"Swrejstepdescr",
"Btrejstepdescr",
"Gwrejstepdescr",
"Domtype",
"Dombehaviour",
"Domname",
"Domdefault",
"Domlinkcode",
"Domlinkname",
"Domcode",
"Nextstepid",
"Nextstepdescr",
"Fromstepid",
"Fromstepdescr",
"AmtField",
"Liabamttyp",
"Bsparamsetid",
"Bsparamsetdescr",
"Field2Src",
"Amount43",
"Curren64",
"Type24",
"Relati29",
"Dateab63",
"Date71",
"DateType",
"RelDate",
"Intege18",
"AccSrc" };

            DisplayNames = new Dictionary<string, GridColumnConfiguration>(){ {"Paramsetdescr" , new GridColumnConfiguration { DisplayName = "Parameter Set"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Prodlongname" , new GridColumnConfiguration { DisplayName = "Product"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Eventlongname" , new GridColumnConfiguration { DisplayName = "Event"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Attachment" , new GridColumnConfiguration { DisplayName = "Attachment"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Mappingtype" , new GridColumnConfiguration { DisplayName = "Mapping Type"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Templateid" , new GridColumnConfiguration { DisplayName = "Template ID"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Optional" , new GridColumnConfiguration { DisplayName = "Option"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Templatedescr" , new GridColumnConfiguration { DisplayName = "Rules"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Typeflag" , new GridColumnConfiguration { DisplayName = "Typeflag"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Operat44" , new GridColumnConfiguration { DisplayName = "Operat44"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Seq97" , new GridColumnConfiguration { DisplayName = "Seq97"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Canamdbas" , new GridColumnConfiguration { DisplayName = "Canamdbas"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Amendchg" , new GridColumnConfiguration { DisplayName = "Amendchg"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Autoprint" , new GridColumnConfiguration { DisplayName = "Autoprint"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Severity" , new GridColumnConfiguration { DisplayName = "Severity"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"ErrorText" , new GridColumnConfiguration { DisplayName = "ErrorText"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Deadlinedays" , new GridColumnConfiguration { DisplayName = "Deadlinedays"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Deadlinedate" , new GridColumnConfiguration { DisplayName = "Deadlinedate"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Deadlinetime" , new GridColumnConfiguration { DisplayName = "Deadlinetime"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Deadlinersecs" , new GridColumnConfiguration { DisplayName = "Deadlinersecs"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Useevtfm" , new GridColumnConfiguration { DisplayName = "Useevtfm"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Username" , new GridColumnConfiguration { DisplayName = "User Name"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Teamcode" , new GridColumnConfiguration { DisplayName = "Team Code"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Obsolete" , new GridColumnConfiguration { DisplayName = "Obsolete"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Relevmapkey" , new GridColumnConfiguration { DisplayName = "Relevmapkey"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Steptype" , new GridColumnConfiguration { DisplayName = "Steptype"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Amberdays" , new GridColumnConfiguration { DisplayName = "Amberdays"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Amberdate" , new GridColumnConfiguration { DisplayName = "Amberdate"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Ambertime" , new GridColumnConfiguration { DisplayName = "Ambertime"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Amberrsecs" , new GridColumnConfiguration { DisplayName = "Amberrsecs"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Reddays" , new GridColumnConfiguration { DisplayName = "Reddays"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Reddate" , new GridColumnConfiguration { DisplayName = "Red Date"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Redtime" , new GridColumnConfiguration { DisplayName = "Red Time"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Redrsecs" , new GridColumnConfiguration { DisplayName = "Redrsecs"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Paramsetid" , new GridColumnConfiguration { DisplayName = "Paramsetid"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Mappingid" , new GridColumnConfiguration { DisplayName = "Mappingid"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Inuse" , new GridColumnConfiguration { DisplayName = "Inuse"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Intinitstepid" , new GridColumnConfiguration { DisplayName = "Intinitstepid"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Swinitstepid" , new GridColumnConfiguration { DisplayName = "Swinitstepid"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Btinitstepid" , new GridColumnConfiguration { DisplayName = "Btinitstepid"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Gwinitstepid" , new GridColumnConfiguration { DisplayName = "Gwinitstepid"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Swrejstepid" , new GridColumnConfiguration { DisplayName = "Swrejstepid"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Btrejstepid" , new GridColumnConfiguration { DisplayName = "Btrejstepid"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Gwrejstepid" , new GridColumnConfiguration { DisplayName = "Gwrejstepid"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Mapstepid" , new GridColumnConfiguration { DisplayName = "Mapstepid"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"StepTime" , new GridColumnConfiguration { DisplayName = "Step Time"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"AvailType" , new GridColumnConfiguration { DisplayName = "Avail Type"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Teamdescr" , new GridColumnConfiguration { DisplayName = "Teamdescr"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Mappingsubid" , new GridColumnConfiguration { DisplayName = "Mappingsubid"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Debitcredit" , new GridColumnConfiguration { DisplayName = "Debitcredit"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Trancode" , new GridColumnConfiguration { DisplayName = "Trancode"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"RevPstngs" , new GridColumnConfiguration { DisplayName = "RevPstngs"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"InternAcc" , new GridColumnConfiguration { DisplayName = "InternAcc"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Contingent" , new GridColumnConfiguration { DisplayName = "Contingent"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Liability" , new GridColumnConfiguration { DisplayName = "Liability"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"ChkLimit" , new GridColumnConfiguration { DisplayName = "ChkLimit"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Postingtyp" , new GridColumnConfiguration { DisplayName = "Postingtyp"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Margin" , new GridColumnConfiguration { DisplayName = "Margin"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Trcrsdliab" , new GridColumnConfiguration { DisplayName = "Trcrsdliab"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"TransAcc" , new GridColumnConfiguration { DisplayName = "TransAcc"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Projection" , new GridColumnConfiguration { DisplayName = "Projection"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Sequence" , new GridColumnConfiguration { DisplayName = "Sequence"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Rejstepid" , new GridColumnConfiguration { DisplayName = "Rejstepid"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"ActualAmt" , new GridColumnConfiguration { DisplayName = "Actual Amount"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"AmtCcy" , new GridColumnConfiguration { DisplayName = "Amount Currency"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Mapstepdescr" , new GridColumnConfiguration { DisplayName = "Mapstepdescr"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Rejstepdescr" , new GridColumnConfiguration { DisplayName = "Rejstepdescr"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Intinitstepdescr" , new GridColumnConfiguration { DisplayName = "Intinitstepdescr"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Swinitstepdescr" , new GridColumnConfiguration { DisplayName = "Swinitstepdescr"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Btinitstepdescr" , new GridColumnConfiguration { DisplayName = "Btinitstepdescr"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Gwinitstepdescr" , new GridColumnConfiguration { DisplayName = "Gwinitstepdescr"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Swrejstepdescr" , new GridColumnConfiguration { DisplayName = "Swrejstepdescr"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Btrejstepdescr" , new GridColumnConfiguration { DisplayName = "Btrejstepdescr"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Gwrejstepdescr" , new GridColumnConfiguration { DisplayName = "Gwrejstepdescr"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Domtype" , new GridColumnConfiguration { DisplayName = "Domtype"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Dombehaviour" , new GridColumnConfiguration { DisplayName = "Dombehaviour"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Domname" , new GridColumnConfiguration { DisplayName = "Domname"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Domdefault" , new GridColumnConfiguration { DisplayName = "Domdefault"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Domlinkcode" , new GridColumnConfiguration { DisplayName = "Domlinkcode"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Domlinkname" , new GridColumnConfiguration { DisplayName = "Domlinkname"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Domcode" , new GridColumnConfiguration { DisplayName = "Domcode"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Nextstepid" , new GridColumnConfiguration { DisplayName = "Nextstepid"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Nextstepdescr" , new GridColumnConfiguration { DisplayName = "Nextstepdescr"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Fromstepid" , new GridColumnConfiguration { DisplayName = "Fromstepid"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Fromstepdescr" , new GridColumnConfiguration { DisplayName = "Fromstepdescr"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"AmtField" , new GridColumnConfiguration { DisplayName = "AmtField"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Liabamttyp" , new GridColumnConfiguration { DisplayName = "Liabamttyp"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Bsparamsetid" , new GridColumnConfiguration { DisplayName = "Bsparamsetid"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Bsparamsetdescr" , new GridColumnConfiguration { DisplayName = "Bsparamsetdescr"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Field2Src" , new GridColumnConfiguration { DisplayName = "Field2Src"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Amount43" , new GridColumnConfiguration { DisplayName = "Amount43"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Curren64" , new GridColumnConfiguration { DisplayName = "Curren64"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Type24" , new GridColumnConfiguration { DisplayName = "Type24"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Relati29" , new GridColumnConfiguration { DisplayName = "Relati29"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Dateab63" , new GridColumnConfiguration { DisplayName = "Dateab63"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Date71" , new GridColumnConfiguration { DisplayName = "Date71"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"DateType" , new GridColumnConfiguration { DisplayName = "Date Type"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"RelDate" , new GridColumnConfiguration { DisplayName = "Rel Date"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"Intege18" , new GridColumnConfiguration { DisplayName = "Intege18"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } },
{"AccSrc" , new GridColumnConfiguration { DisplayName = "AccSrc"  , Format = ""  ,  Filter = "" , Template = "" , AggText = ""  , isLargeText = false   } } };







        }
    }
}