using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace OracleMigrations.Migrations.AmlAnalysis
{
    public partial class addAmlAnalysisModule : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql($@"create or replace VIEW ART.ART_ALERTS_STATUS_CUSTOMER as select  alerted_entity_number , count(*) CLOSED_ALERTS_COUNT from fcfkc.fsk_alert 
                                        where alert_status_code in ('CLC','CLS','FPO') group by alerted_entity_number");



            migrationBuilder.Sql($@"CREATE or replace VIEW ART.ART_AML_ANALYSIS_VIEW AS
  select seg.MONTH_KEY,seg.PARTY_NUMBER,seg.RISK_CLASSIFICATION,seg.PARTY_TYPE_DESC,seg.INDUSTRY_CODE,seg.INDUSTRY_DESC,pd.OCCUPATION_CODE,pd.OCCUPATION_DESC
  ,seg.TOTAL_CREDIT_AMOUNT,seg.TOTAL_DEBIT_AMOUNT,seg.TOTAL_CREDIT_CNT,seg.TOTAL_DEBIT_CNT,seg.TOTAL_AMOUNT,seg.TOTAL_CNT,seg.NUMBER_OF_LOCATIONS,
  seg.AVG_WIRE_C_AMT,seg.MAX_WIRE_C_AMT,seg.TOTAL_WIRE_C_AMT,seg.MIN_WIRE_C_AMT,seg.TOTAL_WIRE_C_CNT,seg.MAX_WIRE_D_AMT,seg.TOTAL_WIRE_D_AMT,seg.TOTAL_WIRE_D_CNT,
  seg.MIN_WIRE_D_AMT,seg.AVG_WIRE_D_AMT,seg.AVG_BUYSECURITY_C_AMT,seg.TOTAL_BUYSECURITY_C_CNT,seg.TOTAL_BUYSECURITY_C_AMT,seg.MIN_BUYSECURITY_C_AMT,
  seg.MAX_BUYSECURITY_C_AMT,seg.TOTAL_CASH_C_AMT,seg.TOTAL_CASH_C_CNT,seg.MIN_CASH_C_AMT,seg.AVG_CASH_C_AMT,seg.MAX_CASH_C_AMT,seg.AVG_CASH_D_AMT,
  seg.TOTAL_CASH_D_AMT,seg.TOTAL_CASH_D_CNT,seg.MIN_CASH_D_AMT,seg.MAX_CASH_D_AMT,seg.TOTAL_CHECK_D_CNT,seg.AVG_CHECK_D_AMT,seg.MAX_CHECK_D_AMT,
  seg.TOTAL_CHECK_D_AMT,seg.MIN_CHECK_D_AMT,seg.MAX_CLEARINGCHECK_C_AMT,seg.MIN_CLEARINGCHECK_C_AMT,seg.AVG_CLEARINGCHECK_C_AMT,seg.TOTAL_CLEARINGCHECK_C_AMT,
  seg.TOTAL_CLEARINGCHECK_C_CNT,seg.MAX_CLEARINGCHECK_D_AMT,seg.AVG_CLEARINGCHECK_D_AMT,seg.TOTAL_CLEARINGCHECK_D_AMT,seg.TOTAL_CLEARINGCHECK_D_CNT,
  seg.MIN_CLEARINGCHECK_D_AMT,seg.AVG_DERIVATIVES_C_AMT,seg.MAX_DERIVATIVES_C_AMT,seg.TOTAL_DERIVATIVES_C_AMT,seg.MIN_DERIVATIVES_C_AMT,
  seg.TOTAL_DERIVATIVES_C_CNT,seg.MAX_DERIVATIVES_D_AMT,seg.TOTAL_DERIVATIVES_D_AMT,seg.TOTAL_DERIVATIVES_D_CNT,seg.MIN_DERIVATIVES_D_AMT,
  seg.AVG_DERIVATIVES_D_AMT,seg.AVG_INHOUSECHECK_C_AMT,seg.TOTAL_INHOUSECHECK_C_AMT,seg.MIN_INHOUSECHECK_C_AMT,seg.MAX_INHOUSECHECK_C_AMT,
  seg.TOTAL_INHOUSECHECK_C_CNT,seg.TOTAL_INHOUSECHECK_D_CNT,seg.AVG_INHOUSECHECK_D_AMT,seg.TOTAL_INHOUSECHECK_D_AMT,seg.MIN_INHOUSECHECK_D_AMT,
  seg.MAX_INHOUSECHECK_D_AMT,seg.MAX_INTERNALTRANSFER_C_AMT,seg.MIN_INTERNALTRANSFER_C_AMT,seg.TOTAL_INTERNALTRANSFER_C_CNT,seg.TOTAL_INTERNALTRANSFER_C_AMT,
  seg.AVG_INTERNALTRANSFER_C_AMT,seg.MIN_INTERNALTRANSFER_D_AMT,seg.TOTAL_INTERNALTRANSFER_D_CNT,seg.AVG_INTERNALTRANSFER_D_AMT,seg.TOTAL_INTERNALTRANSFER_D_AMT,
  seg.MAX_INTERNALTRANSFER_D_AMT,seg.MAX_LC_BL_CLCN_C_AMT,seg.MIN_LC_BL_CLCN_C_AMT,seg.TOTAL_LC_BL_CLCN_C_CNT,seg.AVG_LC_BL_CLCN_C_AMT,seg.TOTAL_LC_BL_CLCN_C_AMT,
  seg.TOTAL_LC_BL_CLCN_D_AMT,seg.MAX_LC_BL_CLCN_D_AMT,seg.MIN_LC_BL_CLCN_D_AMT,seg.AVG_LC_BL_CLCN_D_AMT,seg.TOTAL_LC_BL_CLCN_D_CNT,seg.TOTAL_LCCOLLECTION_C_CNT,
  seg.MAX_LCCOLLECTION_C_AMT,seg.AVG_LCCOLLECTION_C_AMT,seg.MIN_LCCOLLECTION_C_AMT,seg.TOTAL_LCCOLLECTION_C_AMT,seg.TOTAL_LCCOLLECTION_D_CNT,
  seg.AVG_LCCOLLECTION_D_AMT,seg.MAX_LCCOLLECTION_D_AMT,seg.TOTAL_LCCOLLECTION_D_AMT,seg.MIN_LCCOLLECTION_D_AMT,seg.TOTAL_LOAN_C_CNT,seg.AVG_LOAN_C_AMT,
  seg.MIN_LOAN_C_AMT,seg.TOTAL_LOAN_C_AMT,seg.MAX_LOAN_C_AMT,seg.TOTAL_LOAN_D_AMT,seg.MAX_LOAN_D_AMT,seg.MIN_LOAN_D_AMT,seg.TOTAL_LOAN_D_CNT,seg.AVG_LOAN_D_AMT,
  seg.MAX_LOANDISBURSEMENT_C_AMT,seg.MIN_LOANDISBURSEMENT_C_AMT,seg.AVG_LOANDISBURSEMENT_C_AMT,seg.TOTAL_LOANDISBURSEMENT_C_AMT,seg.TOTAL_LOANDISBURSEMENT_C_CNT,
  seg.AVG_LOANTOP_UP_C_AMT,seg.MIN_LOANTOP_UP_C_AMT,seg.TOTAL_LOANTOP_UP_C_AMT,seg.TOTAL_LOANTOP_UP_C_CNT,seg.MAX_LOANTOP_UP_C_AMT,seg.AVG_MNGRSCHCKISSNCE_C_AMT,
  seg.TOTAL_MNGRSCHCKISSNCE_C_CNT,seg.MAX_MNGRSCHCKISSNCE_C_AMT,seg.MIN_MNGRSCHCKISSNCE_C_AMT,seg.TOTAL_MNGRSCHCKISSNCE_C_AMT,seg.MAX_MNGRSCHCKISSNCE_D_AMT,
  seg.TOTAL_MNGRSCHCKISSNCE_D_AMT,seg.MIN_MNGRSCHCKISSNCE_D_AMT,seg.TOTAL_MNGRSCHCKISSNCE_D_CNT,seg.AVG_MNGRSCHCKISSNCE_D_AMT,seg.TOTAL_MISC_C_CNT,seg.AVG_MISC_C_AMT,
  seg.TOTAL_MISC_C_AMT,seg.MIN_MISC_C_AMT,seg.MAX_MISC_C_AMT,seg.TOTAL_MISC_D_AMT,seg.AVG_MISC_D_AMT,seg.MAX_MISC_D_AMT,seg.MIN_MISC_D_AMT,seg.TOTAL_MISC_D_CNT,
  seg.AVG_OUTWRDCHQRTRN_D_AMT,seg.TOTAL_OUTWRDCHQRTRN_D_CNT,seg.TOTAL_OUTWRDCHQRTRN_D_AMT,seg.MIN_OUTWRDCHQRTRN_D_AMT,seg.MAX_OUTWRDCHQRTRN_D_AMT,
  seg.AVG_PYMNTOFINSTLLMNT_D_AMT,seg.TOTAL_PYMNTOFINSTLLMNT_D_CNT,seg.TOTAL_PYMNTOFINSTLLMNT_D_AMT,seg.MIN_PYMNTOFINSTLLMNT_D_AMT,seg.MAX_PYMNTOFINSTLLMNT_D_AMT,
  seg.AVG_RETURNEDWIRES_D_AMT,seg.MAX_RETURNEDWIRES_D_AMT,seg.TOTAL_RETURNEDWIRES_D_AMT,seg.MIN_RETURNEDWIRES_D_AMT,seg.TOTAL_RETURNEDWIRES_D_CNT,
  seg.MAX_RETURNCHEQUE_C_AMT,seg.TOTAL_RETURNCHEQUE_C_AMT,seg.TOTAL_RETURNCHEQUE_C_CNT,seg.MIN_RETURNCHEQUE_C_AMT,seg.AVG_RETURNCHEQUE_C_AMT,
  seg.TOTAL_SALARYCREDIT_C_AMT,seg.TOTAL_SALARYCREDIT_C_CNT,seg.MIN_SALARYCREDIT_C_AMT,seg.AVG_SALARYCREDIT_C_AMT,seg.MAX_SALARYCREDIT_C_AMT,
  seg.AVG_SALARYDEBIT_D_AMT,seg.TOTAL_SALARYDEBIT_D_AMT,seg.TOTAL_SALARYDEBIT_D_CNT,seg.MIN_SALARYDEBIT_D_AMT,seg.MAX_SALARYDEBIT_D_AMT,
  seg.TOTAL_SECURITIES_C_CNT,seg.AVG_SECURITIES_C_AMT,seg.MAX_SECURITIES_C_AMT,seg.TOTAL_SECURITIES_C_AMT,seg.MIN_SECURITIES_C_AMT,seg.MAX_SECURITIES_D_AMT,
  seg.MIN_SECURITIES_D_AMT,seg.AVG_SECURITIES_D_AMT,seg.TOTAL_SECURITIES_D_AMT,seg.TOTAL_SECURITIES_D_CNT,seg.MAX_SELLSECURITY_D_AMT,seg.AVG_SELLSECURITY_D_AMT,
  seg.TOTAL_SELLSECURITY_D_AMT,seg.TOTAL_SELLSECURITY_D_CNT,seg.MIN_SELLSECURITY_D_AMT,seg.TOTAL_TDREDEMPTION_C_AMT,seg.TOTAL_TDREDEMPTION_C_CNT,
  seg.MIN_TDREDEMPTION_C_AMT,seg.AVG_TDREDEMPTION_C_AMT,seg.MAX_TDREDEMPTION_C_AMT,seg.AVG_TDREDEMPTION_D_AMT,seg.TOTAL_TDREDEMPTION_D_AMT,
  seg.TOTAL_TDREDEMPTION_D_CNT,seg.MIN_TDREDEMPTION_D_AMT,seg.MAX_TDREDEMPTION_D_AMT,seg.TOTAL_TERMDEPOSIT_C_CNT,seg.AVG_TERMDEPOSIT_C_AMT,
  seg.MAX_TERMDEPOSIT_C_AMT,seg.TOTAL_TERMDEPOSIT_C_AMT,seg.MIN_TERMDEPOSIT_C_AMT,seg.MAX_TERMDEPOSIT_D_AMT,seg.MIN_TERMDEPOSIT_D_AMT,
  seg.AVG_TERMDEPOSIT_D_AMT,seg.TOTAL_TERMDEPOSIT_D_AMT,seg.TOTAL_TERMDEPOSIT_D_CNT,seg.MAX_TTISSUANCE_D_AMT,seg.AVG_TTISSUANCE_D_AMT,
  seg.TOTAL_TTISSUANCE_D_AMT,seg.TOTAL_TTISSUANCE_D_CNT,seg.MIN_TTISSUANCE_D_AMT,AE.MONEY_LAUNDERING_SCORE as MAX_MLS ,seg.ALERTS_CNT , 
  --this comment for sake of make it works on oracle 96 you must remove it at bank
    --pd.ENTITY_SEGMENT_ID as SEGMENT,
    --pd.ENTITY_SEGMENT_ID as SEGMENT_SORTED , 
  pd.party_name ,round(Preds.PRED ,3) as Prediction  
  ,AE.ALERTS_CNT as Alerts_Count , alc.Closed_Alerts_Count as Closed_Alerts_Count
from fcfcore.fsc_party_dim  pd inner join FCFCORE.YR_BFR_ALRT_PRFL_V3  seg on pd.PARTY_NUMBER = seg.PARTY_NUMBER 
inner join fcfkc.FSK_ALERTED_ENTITY  AE on Ae.ALERTED_ENTITY_NUMBER = seg.PARTY_NUMBER
inner join FCFKC.AUTO_SUPP_PREDS  Preds on Preds.PARTY_NUMBER = seg.PARTY_NUMBER
left join ART.ART_ALERTS_STATUS_CUSTOMER  alc on alc.ALERTED_ENTITY_NUMBER = Ae.ALERTED_ENTITY_NUMBER
where pd.CHANGE_CURRENT_IND = 'Y' 
and ( AE.ALERTS_CNT >0 )");



            migrationBuilder.Sql($@"declare
   c int;
begin
   select count(*) into c from user_tables where table_name = upper('ART_AML_ANALYSIS_VIEW_TB');
   if c > 0 then
      execute immediate 'drop table ART_AML_ANALYSIS_VIEW_TB';
   end if;
     execute immediate 'CREATE TABLE ART_AML_ANALYSIS_VIEW_TB AS SELECT * FROM ART_AML_ANALYSIS_VIEW';
end;");

        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
