// <auto-generated />
using System;
using Data.Data.FATCA;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace SqlServerMigrations.Migrations.FATCA
{
    [DbContext(typeof(FATCAContext))]
    partial class FATCAContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Data.DATA.FATCA.ArtFatcaAlert", b =>
                {
                    b.Property<string>("BranchName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("branch_name")
                        .UseCollation("Arabic_CI_AI");

                    b.Property<string>("CaseId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("case_id")
                        .UseCollation("Arabic_100_CI_AI");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime")
                        .HasColumnName("CREATE_DATE");

                    b.Property<string>("CustomerId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Customer_ID")
                        .UseCollation("Arabic_CI_AS");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Customer_Name")
                        .UseCollation("Arabic_CI_AS");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .UseCollation("Arabic_100_CI_AI");

                    b.Property<string>("IncidentId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("Incident_ID")
                        .UseCollation("Arabic_100_CI_AI");

                    b.Property<string>("Type")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .UseCollation("Arabic_100_CI_AI");

                    b.ToView("ART_FATCA_ALERTS", "ART_DB");
                });

            modelBuilder.Entity("Data.DATA.FATCA.ArtFatcaCace", b =>
                {
                    b.Property<string>("BranchName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("branch_name")
                        .UseCollation("Arabic_CI_AI");

                    b.Property<string>("CaseId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("case_id")
                        .UseCollation("Arabic_100_CI_AI");

                    b.Property<string>("CaseStatus")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("case_status")
                        .UseCollation("Arabic_100_CI_AI");

                    b.Property<string>("CaseType")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("case_type")
                        .UseCollation("Arabic_100_CI_AI");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime")
                        .HasColumnName("CREATE_DATE");

                    b.Property<string>("CustomerId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Customer_ID")
                        .UseCollation("Arabic_CI_AS");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Customer_Name")
                        .UseCollation("Arabic_CI_AS");

                    b.ToView("ART_FATCA_CACES", "ART_DB");
                });

            modelBuilder.Entity("Data.DATA.FATCA.ArtFatcaCustomer", b =>
                {
                    b.Property<string>("BranchName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("branch_name")
                        .UseCollation("Arabic_CI_AI");

                    b.Property<string>("CaseId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("case_id")
                        .UseCollation("Arabic_100_CI_AI");

                    b.Property<string>("CaseStatus")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("case_status")
                        .UseCollation("Arabic_100_CI_AI");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime")
                        .HasColumnName("CREATE_DATE");

                    b.Property<string>("CustClsFlag")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("CUST_CLS_FLAG")
                        .IsFixedLength()
                        .UseCollation("Arabic_CI_AS");

                    b.Property<decimal?>("CustKey")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("cust_key");

                    b.Property<string>("CustomerId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Customer_ID")
                        .UseCollation("Arabic_CI_AS");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Customer_Name")
                        .UseCollation("Arabic_CI_AS");

                    b.Property<string>("MainNationality")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("Main_Nationality")
                        .UseCollation("Arabic_100_CI_AI");

                    b.Property<string>("SignW8")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("SIGN_W8")
                        .UseCollation("Arabic_CI_AS");

                    b.Property<string>("SignW9")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("SIGN_W9")
                        .UseCollation("Arabic_CI_AS");

                    b.Property<DateTime?>("W8SignDate")
                        .HasColumnType("datetime")
                        .HasColumnName("W8_SIGN_DATE");

                    b.Property<DateTime?>("W9SignDate")
                        .HasColumnType("datetime")
                        .HasColumnName("W9_SIGN_DATE");

                    b.ToView("ART_FATCA_CUSTOMERS", "ART_DB");
                });

            modelBuilder.Entity("Data.DATA.FATCA.ArtFatcaDormantAccountsSummary", b =>
                {
                    b.Property<decimal?>("AmountInUsd")
                        .HasColumnType("numeric(38,6)")
                        .HasColumnName("AMOUNT_IN_USD");

                    b.Property<decimal?>("NumberOfAccounts")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("NUMBER_OF_ACCOUNTS");

                    b.ToView("ART_FATCA_DORMANT_ACCOUNTS_SUMMARY", "ART_DB");
                });

            modelBuilder.Entity("Data.DATA.FATCA.ArtFatcaIrsReport", b =>
                {
                    b.Property<decimal?>("Accountbalance")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ACCOUNTBALANCE");

                    b.Property<string>("Accountclosed")
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("ACCOUNTCLOSED");

                    b.Property<string>("AccountcountFatca201")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("ACCOUNTCOUNT_FATCA201");

                    b.Property<string>("AccountcountFatca202")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("ACCOUNTCOUNT_FATCA202");

                    b.Property<decimal?>("AccountcountFatca203")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ACCOUNTCOUNT_FATCA203");

                    b.Property<string>("AccountcountFatca204")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("ACCOUNTCOUNT_FATCA204");

                    b.Property<string>("AccountcountFatca205")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("ACCOUNTCOUNT_FATCA205");

                    b.Property<string>("AccountcountFatca206")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("ACCOUNTCOUNT_FATCA206");

                    b.Property<string>("Accountholdertype")
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("ACCOUNTHOLDERTYPE");

                    b.Property<string>("Accountnumber")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ACCOUNTNUMBER")
                        .UseCollation("Arabic_CI_AS");

                    b.Property<string>("Accounttype")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("ACCOUNTTYPE");

                    b.Property<string>("AddressfreeE")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("ADDRESSFREE_E")
                        .UseCollation("Arabic_CI_AS");

                    b.Property<string>("AddressfreeI")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("ADDRESSFREE_I")
                        .UseCollation("Arabic_CI_AS");

                    b.Property<string>("Birthdate")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("BIRTHDATE");

                    b.Property<string>("Countrycode")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("COUNTRYCODE")
                        .UseCollation("Arabic_CI_AS");

                    b.Property<string>("Countrycodeadd")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("COUNTRYCODEADD")
                        .UseCollation("Arabic_CI_AS");

                    b.Property<string>("Firstname")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("FIRSTNAME")
                        .UseCollation("Arabic_CI_AS");

                    b.Property<string>("Lastname")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("LASTNAME")
                        .UseCollation("Arabic_CI_AS");

                    b.Property<string>("Middlename")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("MIDDLENAME")
                        .UseCollation("Arabic_CI_AS");

                    b.Property<string>("Nationality")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("NATIONALITY")
                        .UseCollation("Arabic_CI_AS");

                    b.Property<string>("OwnerAddress")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("OWNER_ADDRESS");

                    b.Property<string>("OwnerFirstName")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("OWNER_FIRST_NAME");

                    b.Property<string>("OwnerLastName")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("OWNER_LAST_NAME");

                    b.Property<string>("OwnerResCountryCode")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("OWNER_RES_COUNTRY_CODE");

                    b.Property<string>("OwnerTin")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("OWNER_TIN");

                    b.Property<decimal?>("Paymentamnt501")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PAYMENTAMNT_501");

                    b.Property<decimal?>("Paymentamnt502")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PAYMENTAMNT_502");

                    b.Property<decimal?>("Paymentamnt503")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PAYMENTAMNT_503");

                    b.Property<decimal?>("Paymentamnt504")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PAYMENTAMNT_504");

                    b.Property<string>("PoolbalanceFatca201")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("POOLBALANCE_FATCA201");

                    b.Property<string>("PoolbalanceFatca202")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("POOLBALANCE_FATCA202");

                    b.Property<decimal?>("PoolbalanceFatca203")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("POOLBALANCE_FATCA203");

                    b.Property<string>("PoolbalanceFatca204")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("POOLBALANCE_FATCA204");

                    b.Property<string>("PoolbalanceFatca205")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("POOLBALANCE_FATCA205");

                    b.Property<string>("PoolbalanceFatca206")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("POOLBALANCE_FATCA206");

                    b.Property<string>("SignW8")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("SIGN_W8")
                        .UseCollation("Arabic_CI_AS");

                    b.Property<string>("SignW9")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("SIGN_W9")
                        .UseCollation("Arabic_CI_AS");

                    b.Property<string>("Tin")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("TIN")
                        .UseCollation("Arabic_CI_AS");

                    b.ToView("ART_FATCA_IRS_REPORT", "ART_DB");
                });
#pragma warning restore 612, 618
        }
    }
}
