// <auto-generated />
using System;
using Data.Data.ARTGOAML;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace OracleMigrations.Migrations.ArtGoAml
{
    [DbContext(typeof(ArtGoAmlContext))]
    partial class ArtGoAmlContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Data.Data.ARTGOAML.ArtGoamlReportsDetail", b =>
                {
                    b.Property<string>("Action")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ACTION")
                        .UseCollation("Arabic_100_CI_AI");

                    b.Property<string>("Currencycodelocal")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("CURRENCYCODELOCAL")
                        .UseCollation("Arabic_100_CI_AI");

                    b.Property<string>("Entityreference")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("ENTITYREFERENCE")
                        .UseCollation("Arabic_100_CI_AI");

                    b.Property<string>("Fiurefnumber")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("FIUREFNUMBER")
                        .UseCollation("Arabic_100_CI_AI");

                    b.Property<int>("Id")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    b.Property<bool?>("Isvalid")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ISVALID");

                    b.Property<DateTime?>("LastUpdatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("LAST_UPDATED_DATE");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("LOCATION")
                        .UseCollation("Arabic_100_CI_AI");

                    b.Property<string>("Priority")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("PRIORITY")
                        .UseCollation("Arabic_100_CI_AI");

                    b.Property<string>("Reason")
                        .HasMaxLength(4000)
                        .HasColumnType("NCLOB")
                        .HasColumnName("REASON")
                        .UseCollation("Arabic_100_CI_AI");

                    b.Property<string>("Rentitybranch")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("RENTITYBRANCH")
                        .UseCollation("Arabic_100_CI_AI");

                    b.Property<int>("Rentityid")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("RENTITYID");

                    b.Property<DateTime?>("Reportcloseddate")
                        .HasColumnType("datetime")
                        .HasColumnName("REPORTCLOSEDDATE");

                    b.Property<string>("Reportcode")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("REPORTCODE")
                        .UseCollation("Arabic_100_CI_AI");

                    b.Property<string>("Reportcreatedby")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("REPORTCREATEDBY")
                        .UseCollation("Arabic_100_CI_AI");

                    b.Property<DateTime?>("Reportcreateddate")
                        .HasColumnType("datetime")
                        .HasColumnName("REPORTCREATEDDATE");

                    b.Property<string>("Reportingpersontype")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("REPORTINGPERSONTYPE")
                        .UseCollation("Arabic_100_CI_AI");

                    b.Property<string>("Reportrisksignificance")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("REPORTRISKSIGNIFICANCE")
                        .UseCollation("Arabic_100_CI_AI");

                    b.Property<string>("Reportstatuscode")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("REPORTSTATUSCODE")
                        .UseCollation("Arabic_100_CI_AI");

                    b.Property<string>("Reportuserlockid")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("REPORTUSERLOCKID")
                        .UseCollation("Arabic_100_CI_AI");

                    b.Property<string>("Reportxml")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("REPORTXML")
                        .UseCollation("Arabic_100_CI_AI");

                    b.Property<string>("Submissioncode")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("SUBMISSIONCODE")
                        .UseCollation("Arabic_100_CI_AI");

                    b.Property<DateTime?>("Submissiondate")
                        .HasColumnType("datetime")
                        .HasColumnName("SUBMISSIONDATE");

                    b.Property<string>("Version")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("VERSION")
                        .UseCollation("Arabic_100_CI_AI");

                    b.ToView("ART_GOAML_REPORTS_DETAILS", "ART_DB");
                });

            modelBuilder.Entity("Data.Data.ARTGOAML.ArtGoamlReportsIndicator", b =>
                {
                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("DESCRIPTION")
                        .UseCollation("Arabic_100_CI_AI");

                    b.Property<string>("Indicator")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("INDICATOR")
                        .UseCollation("Arabic_100_CI_AI");

                    b.Property<int>("ReportId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("REPORT_ID");

                    b.ToView("ART_GOAML_REPORTS_INDICATORS", "ART_DB");
                });

            modelBuilder.Entity("Data.Data.ARTGOAML.ArtGoamlReportsSusbectParty", b =>
                {
                    b.Property<string>("Account")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("ACCOUNT")
                        .UseCollation("Arabic_100_CI_AI");

                    b.Property<string>("Activity")
                        .IsRequired()
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(12)")
                        .HasColumnName("ACTIVITY");

                    b.Property<string>("Branch")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("BRANCH")
                        .UseCollation("Arabic_100_CI_AI");

                    b.Property<string>("Entityreference")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("ENTITYREFERENCE")
                        .UseCollation("Arabic_100_CI_AI");

                    b.Property<string>("Fiurefnumber")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("FIUREFNUMBER")
                        .UseCollation("Arabic_100_CI_AI");

                    b.Property<int>("Id")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    b.Property<string>("PartyId")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("PARTY_ID")
                        .UseCollation("Arabic_100_CI_AI");

                    b.Property<string>("PartyName")
                        .HasMaxLength(765)
                        .HasColumnType("NVARCHAR2(765)")
                        .HasColumnName("PARTY_NAME")
                        .UseCollation("Arabic_100_CI_AI");

                    b.Property<string>("Partynumber")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("PARTYNUMBER")
                        .UseCollation("Arabic_100_CI_AI");

                    b.Property<DateTime?>("Reportcloseddate")
                        .HasColumnType("datetime")
                        .HasColumnName("REPORTCLOSEDDATE");

                    b.Property<string>("Reportcode")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("REPORTCODE")
                        .UseCollation("Arabic_100_CI_AI");

                    b.Property<DateTime?>("Reportcreateddate")
                        .HasColumnType("datetime")
                        .HasColumnName("REPORTCREATEDDATE");

                    b.Property<string>("Reportstatuscode")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("REPORTSTATUSCODE")
                        .UseCollation("Arabic_100_CI_AI");

                    b.Property<DateTime?>("Submissiondate")
                        .HasColumnType("datetime")
                        .HasColumnName("SUBMISSIONDATE");

                    b.Property<string>("Transactionnumber")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("TRANSACTIONNUMBER")
                        .UseCollation("Arabic_100_CI_AI");

                    b.ToView("ART_GOAML_REPORTS_SUSBECT_PARTIES", "ART_DB");
                });
#pragma warning restore 612, 618
        }
    }
}
