// <auto-generated />
using System;
using Data.Data.AmlAnalysis;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace SqlServerMigrations.Migrations.AmlAnalysis
{
    [DbContext(typeof(AmlAnalysisContext))]
    partial class AmlAnalysisContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ART")
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Data.Data.AmlAnalysis.ArtAlertsStatusCustomer", b =>
                {
                    b.Property<string>("AlertedEntityNumber")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ALERTED_ENTITY_NUMBER");

                    b.Property<decimal?>("ClosedAlertsCount")
                        .HasColumnType("NUMBER")
                        .HasColumnName("CLOSED_ALERTS_COUNT");

                    b.ToView("ART_ALERTS_STATUS_CUSTOMER");
                });

            modelBuilder.Entity("Data.Data.AmlAnalysis.ArtAmlAnalysisRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Action")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("ReadableOutPut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RouteToUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sql")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ArtAmlAnalysisRules", "ART");
                });

            modelBuilder.Entity("Data.Data.AmlAnalysis.ArtAmlAnalysisView", b =>
                {
                    b.Property<decimal?>("AlertsCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("ALERTS_CNT");

                    b.Property<int?>("AlertsCount")
                        .HasPrecision(6)
                        .HasColumnType("int")
                        .HasColumnName("ALERTS_COUNT");

                    b.Property<decimal?>("AvgBuysecurityCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVG_BUYSECURITY_C_AMT");

                    b.Property<decimal?>("AvgCashCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVG_CASH_C_AMT");

                    b.Property<decimal?>("AvgCashDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVG_CASH_D_AMT");

                    b.Property<decimal?>("AvgCheckDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVG_CHECK_D_AMT");

                    b.Property<decimal?>("AvgClearingcheckCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVG_CLEARINGCHECK_C_AMT");

                    b.Property<decimal?>("AvgClearingcheckDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVG_CLEARINGCHECK_D_AMT");

                    b.Property<decimal?>("AvgDerivativesCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVG_DERIVATIVES_C_AMT");

                    b.Property<decimal?>("AvgDerivativesDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVG_DERIVATIVES_D_AMT");

                    b.Property<decimal?>("AvgInhousecheckCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVG_INHOUSECHECK_C_AMT");

                    b.Property<decimal?>("AvgInhousecheckDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVG_INHOUSECHECK_D_AMT");

                    b.Property<decimal?>("AvgInternaltransferCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVG_INTERNALTRANSFER_C_AMT");

                    b.Property<decimal?>("AvgInternaltransferDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVG_INTERNALTRANSFER_D_AMT");

                    b.Property<decimal?>("AvgLcBlClcnCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVG_LC_BL_CLCN_C_AMT");

                    b.Property<decimal?>("AvgLcBlClcnDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVG_LC_BL_CLCN_D_AMT");

                    b.Property<decimal?>("AvgLccollectionCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVG_LCCOLLECTION_C_AMT");

                    b.Property<decimal?>("AvgLccollectionDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVG_LCCOLLECTION_D_AMT");

                    b.Property<decimal?>("AvgLoanCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVG_LOAN_C_AMT");

                    b.Property<decimal?>("AvgLoanDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVG_LOAN_D_AMT");

                    b.Property<decimal?>("AvgLoandisbursementCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVG_LOANDISBURSEMENT_C_AMT");

                    b.Property<decimal?>("AvgLoantopUpCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVG_LOANTOP_UP_C_AMT");

                    b.Property<decimal?>("AvgMiscCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVG_MISC_C_AMT");

                    b.Property<decimal?>("AvgMiscDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVG_MISC_D_AMT");

                    b.Property<decimal?>("AvgMngrschckissnceCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVG_MNGRSCHCKISSNCE_C_AMT");

                    b.Property<decimal?>("AvgMngrschckissnceDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVG_MNGRSCHCKISSNCE_D_AMT");

                    b.Property<decimal?>("AvgOutwrdchqrtrnDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVG_OUTWRDCHQRTRN_D_AMT");

                    b.Property<decimal?>("AvgPymntofinstllmntDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVG_PYMNTOFINSTLLMNT_D_AMT");

                    b.Property<decimal?>("AvgReturnchequeCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVG_RETURNCHEQUE_C_AMT");

                    b.Property<decimal?>("AvgReturnedwiresDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVG_RETURNEDWIRES_D_AMT");

                    b.Property<decimal?>("AvgSalarycreditCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVG_SALARYCREDIT_C_AMT");

                    b.Property<decimal?>("AvgSalarydebitDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVG_SALARYDEBIT_D_AMT");

                    b.Property<decimal?>("AvgSecuritiesCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVG_SECURITIES_C_AMT");

                    b.Property<decimal?>("AvgSecuritiesDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVG_SECURITIES_D_AMT");

                    b.Property<decimal?>("AvgSellsecurityDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVG_SELLSECURITY_D_AMT");

                    b.Property<decimal?>("AvgTdredemptionCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVG_TDREDEMPTION_C_AMT");

                    b.Property<decimal?>("AvgTdredemptionDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVG_TDREDEMPTION_D_AMT");

                    b.Property<decimal?>("AvgTermdepositCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVG_TERMDEPOSIT_C_AMT");

                    b.Property<decimal?>("AvgTermdepositDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVG_TERMDEPOSIT_D_AMT");

                    b.Property<decimal?>("AvgTtissuanceDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVG_TTISSUANCE_D_AMT");

                    b.Property<decimal?>("AvgWireCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVG_WIRE_C_AMT");

                    b.Property<decimal?>("AvgWireDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVG_WIRE_D_AMT");

                    b.Property<decimal?>("ClosedAlertsCount")
                        .HasColumnType("NUMBER")
                        .HasColumnName("CLOSED_ALERTS_COUNT");

                    b.Property<string>("IndustryCode")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("char(10)")
                        .HasColumnName("INDUSTRY_CODE")
                        .IsFixedLength();

                    b.Property<string>("IndustryDesc")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("INDUSTRY_DESC");

                    b.Property<decimal?>("MaxBuysecurityCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_BUYSECURITY_C_AMT");

                    b.Property<decimal?>("MaxCashCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_CASH_C_AMT");

                    b.Property<decimal?>("MaxCashDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_CASH_D_AMT");

                    b.Property<decimal?>("MaxCheckDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_CHECK_D_AMT");

                    b.Property<decimal?>("MaxClearingcheckCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_CLEARINGCHECK_C_AMT");

                    b.Property<decimal?>("MaxClearingcheckDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_CLEARINGCHECK_D_AMT");

                    b.Property<decimal?>("MaxDerivativesCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_DERIVATIVES_C_AMT");

                    b.Property<decimal?>("MaxDerivativesDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_DERIVATIVES_D_AMT");

                    b.Property<decimal?>("MaxInhousecheckCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_INHOUSECHECK_C_AMT");

                    b.Property<decimal?>("MaxInhousecheckDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_INHOUSECHECK_D_AMT");

                    b.Property<decimal?>("MaxInternaltransferCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_INTERNALTRANSFER_C_AMT");

                    b.Property<decimal?>("MaxInternaltransferDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_INTERNALTRANSFER_D_AMT");

                    b.Property<decimal?>("MaxLcBlClcnCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_LC_BL_CLCN_C_AMT");

                    b.Property<decimal?>("MaxLcBlClcnDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_LC_BL_CLCN_D_AMT");

                    b.Property<decimal?>("MaxLccollectionCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_LCCOLLECTION_C_AMT");

                    b.Property<decimal?>("MaxLccollectionDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_LCCOLLECTION_D_AMT");

                    b.Property<decimal?>("MaxLoanCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_LOAN_C_AMT");

                    b.Property<decimal?>("MaxLoanDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_LOAN_D_AMT");

                    b.Property<decimal?>("MaxLoandisbursementCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_LOANDISBURSEMENT_C_AMT");

                    b.Property<decimal?>("MaxLoantopUpCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_LOANTOP_UP_C_AMT");

                    b.Property<decimal?>("MaxMiscCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_MISC_C_AMT");

                    b.Property<decimal?>("MaxMiscDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_MISC_D_AMT");

                    b.Property<int?>("MaxMls")
                        .HasPrecision(6)
                        .HasColumnType("int")
                        .HasColumnName("MAX_MLS");

                    b.Property<decimal?>("MaxMngrschckissnceCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_MNGRSCHCKISSNCE_C_AMT");

                    b.Property<decimal?>("MaxMngrschckissnceDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_MNGRSCHCKISSNCE_D_AMT");

                    b.Property<decimal?>("MaxOutwrdchqrtrnDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_OUTWRDCHQRTRN_D_AMT");

                    b.Property<decimal?>("MaxPymntofinstllmntDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_PYMNTOFINSTLLMNT_D_AMT");

                    b.Property<decimal?>("MaxReturnchequeCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_RETURNCHEQUE_C_AMT");

                    b.Property<decimal?>("MaxReturnedwiresDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_RETURNEDWIRES_D_AMT");

                    b.Property<decimal?>("MaxSalarycreditCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_SALARYCREDIT_C_AMT");

                    b.Property<decimal?>("MaxSalarydebitDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_SALARYDEBIT_D_AMT");

                    b.Property<decimal?>("MaxSecuritiesCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_SECURITIES_C_AMT");

                    b.Property<decimal?>("MaxSecuritiesDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_SECURITIES_D_AMT");

                    b.Property<decimal?>("MaxSellsecurityDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_SELLSECURITY_D_AMT");

                    b.Property<decimal?>("MaxTdredemptionCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_TDREDEMPTION_C_AMT");

                    b.Property<decimal?>("MaxTdredemptionDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_TDREDEMPTION_D_AMT");

                    b.Property<decimal?>("MaxTermdepositCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_TERMDEPOSIT_C_AMT");

                    b.Property<decimal?>("MaxTermdepositDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_TERMDEPOSIT_D_AMT");

                    b.Property<decimal?>("MaxTtissuanceDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_TTISSUANCE_D_AMT");

                    b.Property<decimal?>("MaxWireCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_WIRE_C_AMT");

                    b.Property<decimal?>("MaxWireDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_WIRE_D_AMT");

                    b.Property<decimal?>("MinBuysecurityCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MIN_BUYSECURITY_C_AMT");

                    b.Property<decimal?>("MinCashCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MIN_CASH_C_AMT");

                    b.Property<decimal?>("MinCashDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MIN_CASH_D_AMT");

                    b.Property<decimal?>("MinCheckDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MIN_CHECK_D_AMT");

                    b.Property<decimal?>("MinClearingcheckCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MIN_CLEARINGCHECK_C_AMT");

                    b.Property<decimal?>("MinClearingcheckDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MIN_CLEARINGCHECK_D_AMT");

                    b.Property<decimal?>("MinDerivativesCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MIN_DERIVATIVES_C_AMT");

                    b.Property<decimal?>("MinDerivativesDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MIN_DERIVATIVES_D_AMT");

                    b.Property<decimal?>("MinInhousecheckCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MIN_INHOUSECHECK_C_AMT");

                    b.Property<decimal?>("MinInhousecheckDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MIN_INHOUSECHECK_D_AMT");

                    b.Property<decimal?>("MinInternaltransferCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MIN_INTERNALTRANSFER_C_AMT");

                    b.Property<decimal?>("MinInternaltransferDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MIN_INTERNALTRANSFER_D_AMT");

                    b.Property<decimal?>("MinLcBlClcnCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MIN_LC_BL_CLCN_C_AMT");

                    b.Property<decimal?>("MinLcBlClcnDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MIN_LC_BL_CLCN_D_AMT");

                    b.Property<decimal?>("MinLccollectionCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MIN_LCCOLLECTION_C_AMT");

                    b.Property<decimal?>("MinLccollectionDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MIN_LCCOLLECTION_D_AMT");

                    b.Property<decimal?>("MinLoanCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MIN_LOAN_C_AMT");

                    b.Property<decimal?>("MinLoanDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MIN_LOAN_D_AMT");

                    b.Property<decimal?>("MinLoandisbursementCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MIN_LOANDISBURSEMENT_C_AMT");

                    b.Property<decimal?>("MinLoantopUpCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MIN_LOANTOP_UP_C_AMT");

                    b.Property<decimal?>("MinMiscCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MIN_MISC_C_AMT");

                    b.Property<decimal?>("MinMiscDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MIN_MISC_D_AMT");

                    b.Property<decimal?>("MinMngrschckissnceCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MIN_MNGRSCHCKISSNCE_C_AMT");

                    b.Property<decimal?>("MinMngrschckissnceDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MIN_MNGRSCHCKISSNCE_D_AMT");

                    b.Property<decimal?>("MinOutwrdchqrtrnDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MIN_OUTWRDCHQRTRN_D_AMT");

                    b.Property<decimal?>("MinPymntofinstllmntDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MIN_PYMNTOFINSTLLMNT_D_AMT");

                    b.Property<decimal?>("MinReturnchequeCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MIN_RETURNCHEQUE_C_AMT");

                    b.Property<decimal?>("MinReturnedwiresDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MIN_RETURNEDWIRES_D_AMT");

                    b.Property<decimal?>("MinSalarycreditCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MIN_SALARYCREDIT_C_AMT");

                    b.Property<decimal?>("MinSalarydebitDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MIN_SALARYDEBIT_D_AMT");

                    b.Property<decimal?>("MinSecuritiesCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MIN_SECURITIES_C_AMT");

                    b.Property<decimal?>("MinSecuritiesDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MIN_SECURITIES_D_AMT");

                    b.Property<decimal?>("MinSellsecurityDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MIN_SELLSECURITY_D_AMT");

                    b.Property<decimal?>("MinTdredemptionCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MIN_TDREDEMPTION_C_AMT");

                    b.Property<decimal?>("MinTdredemptionDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MIN_TDREDEMPTION_D_AMT");

                    b.Property<decimal?>("MinTermdepositCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MIN_TERMDEPOSIT_C_AMT");

                    b.Property<decimal?>("MinTermdepositDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MIN_TERMDEPOSIT_D_AMT");

                    b.Property<decimal?>("MinTtissuanceDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MIN_TTISSUANCE_D_AMT");

                    b.Property<decimal?>("MinWireCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MIN_WIRE_C_AMT");

                    b.Property<decimal?>("MinWireDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MIN_WIRE_D_AMT");

                    b.Property<string>("MonthKey")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("MONTH_KEY");

                    b.Property<decimal?>("NumberOfLocations")
                        .HasColumnType("NUMBER")
                        .HasColumnName("NUMBER_OF_LOCATIONS");

                    b.Property<string>("OccupationCode")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("OCCUPATION_CODE");

                    b.Property<string>("OccupationDesc")
                        .HasMaxLength(55)
                        .IsUnicode(false)
                        .HasColumnType("varchar(55)")
                        .HasColumnName("OCCUPATION_DESC");

                    b.Property<string>("PartyName")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("PARTY_NAME");

                    b.Property<string>("PartyNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("PARTY_NUMBER");

                    b.Property<string>("PartyTypeDesc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("PARTY_TYPE_DESC");

                    b.Property<decimal?>("Prediction")
                        .HasColumnType("NUMBER")
                        .HasColumnName("PREDICTION");

                    b.Property<bool?>("RiskClassification")
                        .HasPrecision(1)
                        .HasColumnType("bit")
                        .HasColumnName("RISK_CLASSIFICATION");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_AMOUNT");

                    b.Property<decimal?>("TotalBuysecurityCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_BUYSECURITY_C_AMT");

                    b.Property<decimal?>("TotalBuysecurityCCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_BUYSECURITY_C_CNT");

                    b.Property<decimal?>("TotalCashCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_CASH_C_AMT");

                    b.Property<decimal?>("TotalCashCCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_CASH_C_CNT");

                    b.Property<decimal?>("TotalCashDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_CASH_D_AMT");

                    b.Property<decimal?>("TotalCashDCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_CASH_D_CNT");

                    b.Property<decimal?>("TotalCheckDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_CHECK_D_AMT");

                    b.Property<decimal?>("TotalCheckDCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_CHECK_D_CNT");

                    b.Property<decimal?>("TotalClearingcheckCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_CLEARINGCHECK_C_AMT");

                    b.Property<decimal?>("TotalClearingcheckCCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_CLEARINGCHECK_C_CNT");

                    b.Property<decimal?>("TotalClearingcheckDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_CLEARINGCHECK_D_AMT");

                    b.Property<decimal?>("TotalClearingcheckDCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_CLEARINGCHECK_D_CNT");

                    b.Property<decimal?>("TotalCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_CNT");

                    b.Property<decimal?>("TotalCreditAmount")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_CREDIT_AMOUNT");

                    b.Property<decimal?>("TotalCreditCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_CREDIT_CNT");

                    b.Property<decimal?>("TotalDebitAmount")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_DEBIT_AMOUNT");

                    b.Property<decimal?>("TotalDebitCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_DEBIT_CNT");

                    b.Property<decimal?>("TotalDerivativesCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_DERIVATIVES_C_AMT");

                    b.Property<decimal?>("TotalDerivativesCCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_DERIVATIVES_C_CNT");

                    b.Property<decimal?>("TotalDerivativesDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_DERIVATIVES_D_AMT");

                    b.Property<decimal?>("TotalDerivativesDCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_DERIVATIVES_D_CNT");

                    b.Property<decimal?>("TotalInhousecheckCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_INHOUSECHECK_C_AMT");

                    b.Property<decimal?>("TotalInhousecheckCCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_INHOUSECHECK_C_CNT");

                    b.Property<decimal?>("TotalInhousecheckDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_INHOUSECHECK_D_AMT");

                    b.Property<decimal?>("TotalInhousecheckDCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_INHOUSECHECK_D_CNT");

                    b.Property<decimal?>("TotalInternaltransferCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_INTERNALTRANSFER_C_AMT");

                    b.Property<decimal?>("TotalInternaltransferCCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_INTERNALTRANSFER_C_CNT");

                    b.Property<decimal?>("TotalInternaltransferDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_INTERNALTRANSFER_D_AMT");

                    b.Property<decimal?>("TotalInternaltransferDCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_INTERNALTRANSFER_D_CNT");

                    b.Property<decimal?>("TotalLcBlClcnCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_LC_BL_CLCN_C_AMT");

                    b.Property<decimal?>("TotalLcBlClcnCCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_LC_BL_CLCN_C_CNT");

                    b.Property<decimal?>("TotalLcBlClcnDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_LC_BL_CLCN_D_AMT");

                    b.Property<decimal?>("TotalLcBlClcnDCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_LC_BL_CLCN_D_CNT");

                    b.Property<decimal?>("TotalLccollectionCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_LCCOLLECTION_C_AMT");

                    b.Property<decimal?>("TotalLccollectionCCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_LCCOLLECTION_C_CNT");

                    b.Property<decimal?>("TotalLccollectionDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_LCCOLLECTION_D_AMT");

                    b.Property<decimal?>("TotalLccollectionDCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_LCCOLLECTION_D_CNT");

                    b.Property<decimal?>("TotalLoanCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_LOAN_C_AMT");

                    b.Property<decimal?>("TotalLoanCCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_LOAN_C_CNT");

                    b.Property<decimal?>("TotalLoanDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_LOAN_D_AMT");

                    b.Property<decimal?>("TotalLoanDCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_LOAN_D_CNT");

                    b.Property<decimal?>("TotalLoandisbursementCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_LOANDISBURSEMENT_C_AMT");

                    b.Property<decimal?>("TotalLoandisbursementCCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_LOANDISBURSEMENT_C_CNT");

                    b.Property<decimal?>("TotalLoantopUpCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_LOANTOP_UP_C_AMT");

                    b.Property<decimal?>("TotalLoantopUpCCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_LOANTOP_UP_C_CNT");

                    b.Property<decimal?>("TotalMiscCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_MISC_C_AMT");

                    b.Property<decimal?>("TotalMiscCCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_MISC_C_CNT");

                    b.Property<decimal?>("TotalMiscDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_MISC_D_AMT");

                    b.Property<decimal?>("TotalMiscDCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_MISC_D_CNT");

                    b.Property<decimal?>("TotalMngrschckissnceCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_MNGRSCHCKISSNCE_C_AMT");

                    b.Property<decimal?>("TotalMngrschckissnceCCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_MNGRSCHCKISSNCE_C_CNT");

                    b.Property<decimal?>("TotalMngrschckissnceDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_MNGRSCHCKISSNCE_D_AMT");

                    b.Property<decimal?>("TotalMngrschckissnceDCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_MNGRSCHCKISSNCE_D_CNT");

                    b.Property<decimal?>("TotalOutwrdchqrtrnDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_OUTWRDCHQRTRN_D_AMT");

                    b.Property<decimal?>("TotalOutwrdchqrtrnDCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_OUTWRDCHQRTRN_D_CNT");

                    b.Property<decimal?>("TotalPymntofinstllmntDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_PYMNTOFINSTLLMNT_D_AMT");

                    b.Property<decimal?>("TotalPymntofinstllmntDCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_PYMNTOFINSTLLMNT_D_CNT");

                    b.Property<decimal?>("TotalReturnchequeCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_RETURNCHEQUE_C_AMT");

                    b.Property<decimal?>("TotalReturnchequeCCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_RETURNCHEQUE_C_CNT");

                    b.Property<decimal?>("TotalReturnedwiresDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_RETURNEDWIRES_D_AMT");

                    b.Property<decimal?>("TotalReturnedwiresDCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_RETURNEDWIRES_D_CNT");

                    b.Property<decimal?>("TotalSalarycreditCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_SALARYCREDIT_C_AMT");

                    b.Property<decimal?>("TotalSalarycreditCCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_SALARYCREDIT_C_CNT");

                    b.Property<decimal?>("TotalSalarydebitDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_SALARYDEBIT_D_AMT");

                    b.Property<decimal?>("TotalSalarydebitDCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_SALARYDEBIT_D_CNT");

                    b.Property<decimal?>("TotalSecuritiesCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_SECURITIES_C_AMT");

                    b.Property<decimal?>("TotalSecuritiesCCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_SECURITIES_C_CNT");

                    b.Property<decimal?>("TotalSecuritiesDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_SECURITIES_D_AMT");

                    b.Property<decimal?>("TotalSecuritiesDCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_SECURITIES_D_CNT");

                    b.Property<decimal?>("TotalSellsecurityDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_SELLSECURITY_D_AMT");

                    b.Property<decimal?>("TotalSellsecurityDCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_SELLSECURITY_D_CNT");

                    b.Property<decimal?>("TotalTdredemptionCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_TDREDEMPTION_C_AMT");

                    b.Property<decimal?>("TotalTdredemptionCCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_TDREDEMPTION_C_CNT");

                    b.Property<decimal?>("TotalTdredemptionDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_TDREDEMPTION_D_AMT");

                    b.Property<decimal?>("TotalTdredemptionDCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_TDREDEMPTION_D_CNT");

                    b.Property<decimal?>("TotalTermdepositCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_TERMDEPOSIT_C_AMT");

                    b.Property<decimal?>("TotalTermdepositCCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_TERMDEPOSIT_C_CNT");

                    b.Property<decimal?>("TotalTermdepositDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_TERMDEPOSIT_D_AMT");

                    b.Property<decimal?>("TotalTermdepositDCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_TERMDEPOSIT_D_CNT");

                    b.Property<decimal?>("TotalTtissuanceDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_TTISSUANCE_D_AMT");

                    b.Property<decimal?>("TotalTtissuanceDCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_TTISSUANCE_D_CNT");

                    b.Property<decimal?>("TotalWireCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_WIRE_C_AMT");

                    b.Property<decimal?>("TotalWireCCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_WIRE_C_CNT");

                    b.Property<decimal?>("TotalWireDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_WIRE_D_AMT");

                    b.Property<decimal?>("TotalWireDCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_WIRE_D_CNT");

                    b.ToView("ART_AML_ANALYSIS_VIEW");
                });

            modelBuilder.Entity("Data.Data.AmlAnalysis.ArtAmlAnalysisViewTb", b =>
                {
                    b.Property<decimal?>("AlertsCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("ALERTS_CNT");

                    b.Property<int?>("AlertsCount")
                        .HasPrecision(6)
                        .HasColumnType("int")
                        .HasColumnName("ALERTS_COUNT");

                    b.Property<decimal?>("AvgBuysecurityCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVG_BUYSECURITY_C_AMT");

                    b.Property<decimal?>("AvgCashCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVG_CASH_C_AMT");

                    b.Property<decimal?>("AvgCashDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVG_CASH_D_AMT");

                    b.Property<decimal?>("AvgCheckDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVG_CHECK_D_AMT");

                    b.Property<decimal?>("AvgClearingcheckCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVG_CLEARINGCHECK_C_AMT");

                    b.Property<decimal?>("AvgClearingcheckDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVG_CLEARINGCHECK_D_AMT");

                    b.Property<decimal?>("AvgDerivativesCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVG_DERIVATIVES_C_AMT");

                    b.Property<decimal?>("AvgDerivativesDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVG_DERIVATIVES_D_AMT");

                    b.Property<decimal?>("AvgInhousecheckCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVG_INHOUSECHECK_C_AMT");

                    b.Property<decimal?>("AvgInhousecheckDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVG_INHOUSECHECK_D_AMT");

                    b.Property<decimal?>("AvgInternaltransferCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVG_INTERNALTRANSFER_C_AMT");

                    b.Property<decimal?>("AvgInternaltransferDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVG_INTERNALTRANSFER_D_AMT");

                    b.Property<decimal?>("AvgLcBlClcnCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVG_LC_BL_CLCN_C_AMT");

                    b.Property<decimal?>("AvgLcBlClcnDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVG_LC_BL_CLCN_D_AMT");

                    b.Property<decimal?>("AvgLccollectionCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVG_LCCOLLECTION_C_AMT");

                    b.Property<decimal?>("AvgLccollectionDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVG_LCCOLLECTION_D_AMT");

                    b.Property<decimal?>("AvgLoanCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVG_LOAN_C_AMT");

                    b.Property<decimal?>("AvgLoanDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVG_LOAN_D_AMT");

                    b.Property<decimal?>("AvgLoandisbursementCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVG_LOANDISBURSEMENT_C_AMT");

                    b.Property<decimal?>("AvgLoantopUpCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVG_LOANTOP_UP_C_AMT");

                    b.Property<decimal?>("AvgMiscCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVG_MISC_C_AMT");

                    b.Property<decimal?>("AvgMiscDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVG_MISC_D_AMT");

                    b.Property<decimal?>("AvgMngrschckissnceCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVG_MNGRSCHCKISSNCE_C_AMT");

                    b.Property<decimal?>("AvgMngrschckissnceDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVG_MNGRSCHCKISSNCE_D_AMT");

                    b.Property<decimal?>("AvgOutwrdchqrtrnDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVG_OUTWRDCHQRTRN_D_AMT");

                    b.Property<decimal?>("AvgPymntofinstllmntDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVG_PYMNTOFINSTLLMNT_D_AMT");

                    b.Property<decimal?>("AvgReturnchequeCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVG_RETURNCHEQUE_C_AMT");

                    b.Property<decimal?>("AvgReturnedwiresDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVG_RETURNEDWIRES_D_AMT");

                    b.Property<decimal?>("AvgSalarycreditCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVG_SALARYCREDIT_C_AMT");

                    b.Property<decimal?>("AvgSalarydebitDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVG_SALARYDEBIT_D_AMT");

                    b.Property<decimal?>("AvgSecuritiesCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVG_SECURITIES_C_AMT");

                    b.Property<decimal?>("AvgSecuritiesDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVG_SECURITIES_D_AMT");

                    b.Property<decimal?>("AvgSellsecurityDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVG_SELLSECURITY_D_AMT");

                    b.Property<decimal?>("AvgTdredemptionCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVG_TDREDEMPTION_C_AMT");

                    b.Property<decimal?>("AvgTdredemptionDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVG_TDREDEMPTION_D_AMT");

                    b.Property<decimal?>("AvgTermdepositCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVG_TERMDEPOSIT_C_AMT");

                    b.Property<decimal?>("AvgTermdepositDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVG_TERMDEPOSIT_D_AMT");

                    b.Property<decimal?>("AvgTtissuanceDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVG_TTISSUANCE_D_AMT");

                    b.Property<decimal?>("AvgWireCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVG_WIRE_C_AMT");

                    b.Property<decimal?>("AvgWireDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("AVG_WIRE_D_AMT");

                    b.Property<decimal?>("ClosedAlertsCount")
                        .HasColumnType("NUMBER")
                        .HasColumnName("CLOSED_ALERTS_COUNT");

                    b.Property<string>("IndustryCode")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("char(10)")
                        .HasColumnName("INDUSTRY_CODE")
                        .IsFixedLength();

                    b.Property<string>("IndustryDesc")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("INDUSTRY_DESC");

                    b.Property<decimal?>("MaxBuysecurityCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_BUYSECURITY_C_AMT");

                    b.Property<decimal?>("MaxCashCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_CASH_C_AMT");

                    b.Property<decimal?>("MaxCashDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_CASH_D_AMT");

                    b.Property<decimal?>("MaxCheckDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_CHECK_D_AMT");

                    b.Property<decimal?>("MaxClearingcheckCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_CLEARINGCHECK_C_AMT");

                    b.Property<decimal?>("MaxClearingcheckDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_CLEARINGCHECK_D_AMT");

                    b.Property<decimal?>("MaxDerivativesCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_DERIVATIVES_C_AMT");

                    b.Property<decimal?>("MaxDerivativesDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_DERIVATIVES_D_AMT");

                    b.Property<decimal?>("MaxInhousecheckCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_INHOUSECHECK_C_AMT");

                    b.Property<decimal?>("MaxInhousecheckDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_INHOUSECHECK_D_AMT");

                    b.Property<decimal?>("MaxInternaltransferCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_INTERNALTRANSFER_C_AMT");

                    b.Property<decimal?>("MaxInternaltransferDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_INTERNALTRANSFER_D_AMT");

                    b.Property<decimal?>("MaxLcBlClcnCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_LC_BL_CLCN_C_AMT");

                    b.Property<decimal?>("MaxLcBlClcnDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_LC_BL_CLCN_D_AMT");

                    b.Property<decimal?>("MaxLccollectionCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_LCCOLLECTION_C_AMT");

                    b.Property<decimal?>("MaxLccollectionDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_LCCOLLECTION_D_AMT");

                    b.Property<decimal?>("MaxLoanCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_LOAN_C_AMT");

                    b.Property<decimal?>("MaxLoanDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_LOAN_D_AMT");

                    b.Property<decimal?>("MaxLoandisbursementCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_LOANDISBURSEMENT_C_AMT");

                    b.Property<decimal?>("MaxLoantopUpCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_LOANTOP_UP_C_AMT");

                    b.Property<decimal?>("MaxMiscCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_MISC_C_AMT");

                    b.Property<decimal?>("MaxMiscDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_MISC_D_AMT");

                    b.Property<int?>("MaxMls")
                        .HasPrecision(6)
                        .HasColumnType("int")
                        .HasColumnName("MAX_MLS");

                    b.Property<decimal?>("MaxMngrschckissnceCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_MNGRSCHCKISSNCE_C_AMT");

                    b.Property<decimal?>("MaxMngrschckissnceDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_MNGRSCHCKISSNCE_D_AMT");

                    b.Property<decimal?>("MaxOutwrdchqrtrnDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_OUTWRDCHQRTRN_D_AMT");

                    b.Property<decimal?>("MaxPymntofinstllmntDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_PYMNTOFINSTLLMNT_D_AMT");

                    b.Property<decimal?>("MaxReturnchequeCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_RETURNCHEQUE_C_AMT");

                    b.Property<decimal?>("MaxReturnedwiresDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_RETURNEDWIRES_D_AMT");

                    b.Property<decimal?>("MaxSalarycreditCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_SALARYCREDIT_C_AMT");

                    b.Property<decimal?>("MaxSalarydebitDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_SALARYDEBIT_D_AMT");

                    b.Property<decimal?>("MaxSecuritiesCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_SECURITIES_C_AMT");

                    b.Property<decimal?>("MaxSecuritiesDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_SECURITIES_D_AMT");

                    b.Property<decimal?>("MaxSellsecurityDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_SELLSECURITY_D_AMT");

                    b.Property<decimal?>("MaxTdredemptionCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_TDREDEMPTION_C_AMT");

                    b.Property<decimal?>("MaxTdredemptionDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_TDREDEMPTION_D_AMT");

                    b.Property<decimal?>("MaxTermdepositCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_TERMDEPOSIT_C_AMT");

                    b.Property<decimal?>("MaxTermdepositDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_TERMDEPOSIT_D_AMT");

                    b.Property<decimal?>("MaxTtissuanceDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_TTISSUANCE_D_AMT");

                    b.Property<decimal?>("MaxWireCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_WIRE_C_AMT");

                    b.Property<decimal?>("MaxWireDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MAX_WIRE_D_AMT");

                    b.Property<decimal?>("MinBuysecurityCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MIN_BUYSECURITY_C_AMT");

                    b.Property<decimal?>("MinCashCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MIN_CASH_C_AMT");

                    b.Property<decimal?>("MinCashDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MIN_CASH_D_AMT");

                    b.Property<decimal?>("MinCheckDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MIN_CHECK_D_AMT");

                    b.Property<decimal?>("MinClearingcheckCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MIN_CLEARINGCHECK_C_AMT");

                    b.Property<decimal?>("MinClearingcheckDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MIN_CLEARINGCHECK_D_AMT");

                    b.Property<decimal?>("MinDerivativesCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MIN_DERIVATIVES_C_AMT");

                    b.Property<decimal?>("MinDerivativesDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MIN_DERIVATIVES_D_AMT");

                    b.Property<decimal?>("MinInhousecheckCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MIN_INHOUSECHECK_C_AMT");

                    b.Property<decimal?>("MinInhousecheckDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MIN_INHOUSECHECK_D_AMT");

                    b.Property<decimal?>("MinInternaltransferCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MIN_INTERNALTRANSFER_C_AMT");

                    b.Property<decimal?>("MinInternaltransferDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MIN_INTERNALTRANSFER_D_AMT");

                    b.Property<decimal?>("MinLcBlClcnCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MIN_LC_BL_CLCN_C_AMT");

                    b.Property<decimal?>("MinLcBlClcnDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MIN_LC_BL_CLCN_D_AMT");

                    b.Property<decimal?>("MinLccollectionCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MIN_LCCOLLECTION_C_AMT");

                    b.Property<decimal?>("MinLccollectionDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MIN_LCCOLLECTION_D_AMT");

                    b.Property<decimal?>("MinLoanCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MIN_LOAN_C_AMT");

                    b.Property<decimal?>("MinLoanDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MIN_LOAN_D_AMT");

                    b.Property<decimal?>("MinLoandisbursementCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MIN_LOANDISBURSEMENT_C_AMT");

                    b.Property<decimal?>("MinLoantopUpCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MIN_LOANTOP_UP_C_AMT");

                    b.Property<decimal?>("MinMiscCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MIN_MISC_C_AMT");

                    b.Property<decimal?>("MinMiscDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MIN_MISC_D_AMT");

                    b.Property<decimal?>("MinMngrschckissnceCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MIN_MNGRSCHCKISSNCE_C_AMT");

                    b.Property<decimal?>("MinMngrschckissnceDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MIN_MNGRSCHCKISSNCE_D_AMT");

                    b.Property<decimal?>("MinOutwrdchqrtrnDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MIN_OUTWRDCHQRTRN_D_AMT");

                    b.Property<decimal?>("MinPymntofinstllmntDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MIN_PYMNTOFINSTLLMNT_D_AMT");

                    b.Property<decimal?>("MinReturnchequeCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MIN_RETURNCHEQUE_C_AMT");

                    b.Property<decimal?>("MinReturnedwiresDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MIN_RETURNEDWIRES_D_AMT");

                    b.Property<decimal?>("MinSalarycreditCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MIN_SALARYCREDIT_C_AMT");

                    b.Property<decimal?>("MinSalarydebitDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MIN_SALARYDEBIT_D_AMT");

                    b.Property<decimal?>("MinSecuritiesCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MIN_SECURITIES_C_AMT");

                    b.Property<decimal?>("MinSecuritiesDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MIN_SECURITIES_D_AMT");

                    b.Property<decimal?>("MinSellsecurityDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MIN_SELLSECURITY_D_AMT");

                    b.Property<decimal?>("MinTdredemptionCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MIN_TDREDEMPTION_C_AMT");

                    b.Property<decimal?>("MinTdredemptionDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MIN_TDREDEMPTION_D_AMT");

                    b.Property<decimal?>("MinTermdepositCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MIN_TERMDEPOSIT_C_AMT");

                    b.Property<decimal?>("MinTermdepositDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MIN_TERMDEPOSIT_D_AMT");

                    b.Property<decimal?>("MinTtissuanceDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MIN_TTISSUANCE_D_AMT");

                    b.Property<decimal?>("MinWireCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MIN_WIRE_C_AMT");

                    b.Property<decimal?>("MinWireDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("MIN_WIRE_D_AMT");

                    b.Property<string>("MonthKey")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("MONTH_KEY");

                    b.Property<decimal?>("NumberOfLocations")
                        .HasColumnType("NUMBER")
                        .HasColumnName("NUMBER_OF_LOCATIONS");

                    b.Property<string>("OccupationCode")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("OCCUPATION_CODE");

                    b.Property<string>("OccupationDesc")
                        .HasMaxLength(55)
                        .IsUnicode(false)
                        .HasColumnType("varchar(55)")
                        .HasColumnName("OCCUPATION_DESC");

                    b.Property<string>("PartyName")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("PARTY_NAME");

                    b.Property<string>("PartyNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("PARTY_NUMBER");

                    b.Property<string>("PartyTypeDesc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("PARTY_TYPE_DESC");

                    b.Property<decimal?>("Prediction")
                        .HasColumnType("NUMBER")
                        .HasColumnName("PREDICTION");

                    b.Property<bool?>("RiskClassification")
                        .HasPrecision(1)
                        .HasColumnType("bit")
                        .HasColumnName("RISK_CLASSIFICATION");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_AMOUNT");

                    b.Property<decimal?>("TotalBuysecurityCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_BUYSECURITY_C_AMT");

                    b.Property<decimal?>("TotalBuysecurityCCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_BUYSECURITY_C_CNT");

                    b.Property<decimal?>("TotalCashCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_CASH_C_AMT");

                    b.Property<decimal?>("TotalCashCCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_CASH_C_CNT");

                    b.Property<decimal?>("TotalCashDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_CASH_D_AMT");

                    b.Property<decimal?>("TotalCashDCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_CASH_D_CNT");

                    b.Property<decimal?>("TotalCheckDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_CHECK_D_AMT");

                    b.Property<decimal?>("TotalCheckDCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_CHECK_D_CNT");

                    b.Property<decimal?>("TotalClearingcheckCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_CLEARINGCHECK_C_AMT");

                    b.Property<decimal?>("TotalClearingcheckCCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_CLEARINGCHECK_C_CNT");

                    b.Property<decimal?>("TotalClearingcheckDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_CLEARINGCHECK_D_AMT");

                    b.Property<decimal?>("TotalClearingcheckDCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_CLEARINGCHECK_D_CNT");

                    b.Property<decimal?>("TotalCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_CNT");

                    b.Property<decimal?>("TotalCreditAmount")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_CREDIT_AMOUNT");

                    b.Property<decimal?>("TotalCreditCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_CREDIT_CNT");

                    b.Property<decimal?>("TotalDebitAmount")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_DEBIT_AMOUNT");

                    b.Property<decimal?>("TotalDebitCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_DEBIT_CNT");

                    b.Property<decimal?>("TotalDerivativesCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_DERIVATIVES_C_AMT");

                    b.Property<decimal?>("TotalDerivativesCCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_DERIVATIVES_C_CNT");

                    b.Property<decimal?>("TotalDerivativesDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_DERIVATIVES_D_AMT");

                    b.Property<decimal?>("TotalDerivativesDCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_DERIVATIVES_D_CNT");

                    b.Property<decimal?>("TotalInhousecheckCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_INHOUSECHECK_C_AMT");

                    b.Property<decimal?>("TotalInhousecheckCCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_INHOUSECHECK_C_CNT");

                    b.Property<decimal?>("TotalInhousecheckDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_INHOUSECHECK_D_AMT");

                    b.Property<decimal?>("TotalInhousecheckDCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_INHOUSECHECK_D_CNT");

                    b.Property<decimal?>("TotalInternaltransferCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_INTERNALTRANSFER_C_AMT");

                    b.Property<decimal?>("TotalInternaltransferCCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_INTERNALTRANSFER_C_CNT");

                    b.Property<decimal?>("TotalInternaltransferDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_INTERNALTRANSFER_D_AMT");

                    b.Property<decimal?>("TotalInternaltransferDCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_INTERNALTRANSFER_D_CNT");

                    b.Property<decimal?>("TotalLcBlClcnCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_LC_BL_CLCN_C_AMT");

                    b.Property<decimal?>("TotalLcBlClcnCCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_LC_BL_CLCN_C_CNT");

                    b.Property<decimal?>("TotalLcBlClcnDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_LC_BL_CLCN_D_AMT");

                    b.Property<decimal?>("TotalLcBlClcnDCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_LC_BL_CLCN_D_CNT");

                    b.Property<decimal?>("TotalLccollectionCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_LCCOLLECTION_C_AMT");

                    b.Property<decimal?>("TotalLccollectionCCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_LCCOLLECTION_C_CNT");

                    b.Property<decimal?>("TotalLccollectionDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_LCCOLLECTION_D_AMT");

                    b.Property<decimal?>("TotalLccollectionDCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_LCCOLLECTION_D_CNT");

                    b.Property<decimal?>("TotalLoanCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_LOAN_C_AMT");

                    b.Property<decimal?>("TotalLoanCCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_LOAN_C_CNT");

                    b.Property<decimal?>("TotalLoanDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_LOAN_D_AMT");

                    b.Property<decimal?>("TotalLoanDCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_LOAN_D_CNT");

                    b.Property<decimal?>("TotalLoandisbursementCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_LOANDISBURSEMENT_C_AMT");

                    b.Property<decimal?>("TotalLoandisbursementCCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_LOANDISBURSEMENT_C_CNT");

                    b.Property<decimal?>("TotalLoantopUpCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_LOANTOP_UP_C_AMT");

                    b.Property<decimal?>("TotalLoantopUpCCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_LOANTOP_UP_C_CNT");

                    b.Property<decimal?>("TotalMiscCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_MISC_C_AMT");

                    b.Property<decimal?>("TotalMiscCCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_MISC_C_CNT");

                    b.Property<decimal?>("TotalMiscDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_MISC_D_AMT");

                    b.Property<decimal?>("TotalMiscDCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_MISC_D_CNT");

                    b.Property<decimal?>("TotalMngrschckissnceCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_MNGRSCHCKISSNCE_C_AMT");

                    b.Property<decimal?>("TotalMngrschckissnceCCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_MNGRSCHCKISSNCE_C_CNT");

                    b.Property<decimal?>("TotalMngrschckissnceDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_MNGRSCHCKISSNCE_D_AMT");

                    b.Property<decimal?>("TotalMngrschckissnceDCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_MNGRSCHCKISSNCE_D_CNT");

                    b.Property<decimal?>("TotalOutwrdchqrtrnDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_OUTWRDCHQRTRN_D_AMT");

                    b.Property<decimal?>("TotalOutwrdchqrtrnDCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_OUTWRDCHQRTRN_D_CNT");

                    b.Property<decimal?>("TotalPymntofinstllmntDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_PYMNTOFINSTLLMNT_D_AMT");

                    b.Property<decimal?>("TotalPymntofinstllmntDCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_PYMNTOFINSTLLMNT_D_CNT");

                    b.Property<decimal?>("TotalReturnchequeCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_RETURNCHEQUE_C_AMT");

                    b.Property<decimal?>("TotalReturnchequeCCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_RETURNCHEQUE_C_CNT");

                    b.Property<decimal?>("TotalReturnedwiresDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_RETURNEDWIRES_D_AMT");

                    b.Property<decimal?>("TotalReturnedwiresDCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_RETURNEDWIRES_D_CNT");

                    b.Property<decimal?>("TotalSalarycreditCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_SALARYCREDIT_C_AMT");

                    b.Property<decimal?>("TotalSalarycreditCCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_SALARYCREDIT_C_CNT");

                    b.Property<decimal?>("TotalSalarydebitDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_SALARYDEBIT_D_AMT");

                    b.Property<decimal?>("TotalSalarydebitDCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_SALARYDEBIT_D_CNT");

                    b.Property<decimal?>("TotalSecuritiesCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_SECURITIES_C_AMT");

                    b.Property<decimal?>("TotalSecuritiesCCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_SECURITIES_C_CNT");

                    b.Property<decimal?>("TotalSecuritiesDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_SECURITIES_D_AMT");

                    b.Property<decimal?>("TotalSecuritiesDCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_SECURITIES_D_CNT");

                    b.Property<decimal?>("TotalSellsecurityDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_SELLSECURITY_D_AMT");

                    b.Property<decimal?>("TotalSellsecurityDCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_SELLSECURITY_D_CNT");

                    b.Property<decimal?>("TotalTdredemptionCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_TDREDEMPTION_C_AMT");

                    b.Property<decimal?>("TotalTdredemptionCCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_TDREDEMPTION_C_CNT");

                    b.Property<decimal?>("TotalTdredemptionDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_TDREDEMPTION_D_AMT");

                    b.Property<decimal?>("TotalTdredemptionDCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_TDREDEMPTION_D_CNT");

                    b.Property<decimal?>("TotalTermdepositCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_TERMDEPOSIT_C_AMT");

                    b.Property<decimal?>("TotalTermdepositCCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_TERMDEPOSIT_C_CNT");

                    b.Property<decimal?>("TotalTermdepositDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_TERMDEPOSIT_D_AMT");

                    b.Property<decimal?>("TotalTermdepositDCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_TERMDEPOSIT_D_CNT");

                    b.Property<decimal?>("TotalTtissuanceDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_TTISSUANCE_D_AMT");

                    b.Property<decimal?>("TotalTtissuanceDCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_TTISSUANCE_D_CNT");

                    b.Property<decimal?>("TotalWireCAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_WIRE_C_AMT");

                    b.Property<decimal?>("TotalWireCCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_WIRE_C_CNT");

                    b.Property<decimal?>("TotalWireDAmt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_WIRE_D_AMT");

                    b.Property<decimal?>("TotalWireDCnt")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TOTAL_WIRE_D_CNT");

                    b.ToTable("ART_AML_ANALYSIS_VIEW_TB", "ART");
                });
#pragma warning restore 612, 618
        }
    }
}
