name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger on pushing tags like v1.0.0, v2.1.3, etc.
  workflow_dispatch:  # Allow manual triggers

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Checks out the repository code

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0  # Ensure the correct .NET version is installed

      - name: Build Solution
        run: dotnet build --configuration Release  # Build the project in Release configuration

      - name: Publish Solution
        run: dotnet publish --configuration Release --output ./publish  # Publish the built project to the ./publish directory

      - name: Create Release
        uses: softprops/action-gh-release@v1  # GitHub Action for creating releases
        with:
          files: ./publish/**  # Attach the built artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authorization
