name: ART Release

on:
  push:
    branches:
      - main
      - ABK
  pull_request:
    branches:
      - main
      - ABK 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.x.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Build and Publish
        run: dotnet publish -r win-x64 --self-contained true -c Release -o ./Release

      - name: Get Version and Tag From Code
        id: set_ver
        run: |
              content=`cat ${{ github.workspace }}/appsettings.json`
              # the following lines are only required for multi line json
              content="${content//'%'/'%25'}"
              content="${content//$'\n'/'%0A'}"
              content="${content//$'\r'/'%0D'}"
              # end of optional handling for multi line json
              echo "::set-output name=packageJson::$content"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{fromJson(steps.set_var.outputs.packageJson).Version}}
          release_name: Release v1.0.2
          body_path: ${{ github.workspace }}/Release_Note.md
          draft: false
          prerelease: false
          
      - name: Zip folder
        run: |
          zip -r Release.zip ./Release
          
      - name: Upload Release Artifact
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/Release.zip
          asset_name: Release.zip # Change the name as needed
          asset_content_type: application/zip
