name: ART Release

on:
  push:
    branches:
      - main
      - ABK
      - MAIN_TEST
      - MIDB
      - TAWKELAT
  pull_request:
    branches:
      - main
      - ABK

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.x.x

      - name: Restore dependencies
        run: dotnet restore

      - name: List Folders
        run: ls

      - name: Build
        run: dotnet build --no-restore

      - name: Build and Publish
        run: dotnet publish -c Release -o ./Release

      - name: Get Version and Tag From Code
        id: set_ver
        run: |
            # Read the JSON file and remove comments (lines starting with // or #)
            content=$(grep -vE '^\s*//' ${{ github.workspace }}/ART_PACKAGE/appsettings.json)
    
            # Handling multi-line JSON for GitHub Actions
            content="${content//'%'/'%25'}"
            content="${content//$'\n'/'%0A'}"
            content="${content//$'\r'/'%0D'}"
    
            # Extract the version using jq (or manually if jq is unavailable)
            version=$(echo "$content" | jq -r '.Version')
    
            # Set outputs for GitHub Actions
            echo "::set-output name=appsettings::$content"
            echo "::set-output name=version::$version"


      - name: Check for existing release
        id: check_release
        run: |
          existing_tag=$(curl -s \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ env.VERSION }} \
            | jq -r '.tag_name')
          if [ "$existing_tag" = "${{ env.VERSION }}" ]; then
            echo "Release with this tag already exists."
            echo "RELEASE_EXISTS=true" >> $GITHUB_ENV
          else
            echo "RELEASE_EXISTS=false" >> $GITHUB_ENV
          fi

      - name: Update or Create Release
        if: env.RELEASE_EXISTS == 'true'
        run: echo "Updating existing release with tag ${{ env.VERSION }}"

      - name: Create a New Release
        id: create_release
        if: env.RELEASE_EXISTS == 'false'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: ${{ env.RELEASE_NAME }}
          body_path: ${{ github.workspace }}/Release_Note.md
          draft: false
          prerelease: false

      - name: Copy ReleaseNote To Release Folder
        run: cp Release_Note.md ./Release

      - name: Zip folder
        run: |
          zip -r Release.zip ./Release

      - name: Upload Release Artifact
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/Release.zip
          asset_name: Release.zip
          asset_content_type: application/zip
